/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constante</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.Constante#getNombre <em>Nombre</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getConstante()
 * @model
 * @generated
 */
public interface Constante extends Expresion
{
  /**
   * Returns the value of the '<em><b>Nombre</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' reference.
   * @see #setNombre(Declaracion)
   * @see upb.lp.edu.madonna.MadonnaPackage#getConstante_Nombre()
   * @model
   * @generated
   */
  Declaracion getNombre();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.Constante#getNombre <em>Nombre</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' reference.
   * @see #getNombre()
   * @generated
   */
  void setNombre(Declaracion value);

} // Constante
