/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaracion</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getDeclaracion()
 * @model
 * @generated
 */
public interface Declaracion extends Instrucciones
{
} // Declaracion
