/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expresion</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getExpresion()
 * @model
 * @generated
 */
public interface Expresion extends Valor
{
} // Expresion
