/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Logica Operadores</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.ExprLogicaOperadores#getOperadorLog <em>Operador Log</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.ExprLogicaOperadores#getExprLogs <em>Expr Logs</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getExprLogicaOperadores()
 * @model
 * @generated
 */
public interface ExprLogicaOperadores extends EObject
{
  /**
   * Returns the value of the '<em><b>Operador Log</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador Log</em>' attribute.
   * @see #setOperadorLog(String)
   * @see upb.lp.edu.madonna.MadonnaPackage#getExprLogicaOperadores_OperadorLog()
   * @model
   * @generated
   */
  String getOperadorLog();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.ExprLogicaOperadores#getOperadorLog <em>Operador Log</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador Log</em>' attribute.
   * @see #getOperadorLog()
   * @generated
   */
  void setOperadorLog(String value);

  /**
   * Returns the value of the '<em><b>Expr Logs</b></em>' containment reference list.
   * The list contents are of type {@link upb.lp.edu.madonna.Expresion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Logs</em>' containment reference list.
   * @see upb.lp.edu.madonna.MadonnaPackage#getExprLogicaOperadores_ExprLogs()
   * @model containment="true"
   * @generated
   */
  EList<Expresion> getExprLogs();

} // ExprLogicaOperadores
