/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Logica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.ExprLogica#isNegado <em>Negado</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.ExprLogica#getExprLog <em>Expr Log</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getExprLogica()
 * @model
 * @generated
 */
public interface ExprLogica extends Expresion
{
  /**
   * Returns the value of the '<em><b>Negado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Negado</em>' attribute.
   * @see #setNegado(boolean)
   * @see upb.lp.edu.madonna.MadonnaPackage#getExprLogica_Negado()
   * @model
   * @generated
   */
  boolean isNegado();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.ExprLogica#isNegado <em>Negado</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Negado</em>' attribute.
   * @see #isNegado()
   * @generated
   */
  void setNegado(boolean value);

  /**
   * Returns the value of the '<em><b>Expr Log</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Log</em>' containment reference.
   * @see #setExprLog(EObject)
   * @see upb.lp.edu.madonna.MadonnaPackage#getExprLogica_ExprLog()
   * @model containment="true"
   * @generated
   */
  EObject getExprLog();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.ExprLogica#getExprLog <em>Expr Log</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr Log</em>' containment reference.
   * @see #getExprLog()
   * @generated
   */
  void setExprLog(EObject value);

} // ExprLogica
