/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.Funcion#getName <em>Name</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.Funcion#getParam <em>Param</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.Funcion#getDeclar <em>Declar</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.Funcion#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getFuncion()
 * @model
 * @generated
 */
public interface Funcion extends Declaracion
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see upb.lp.edu.madonna.MadonnaPackage#getFuncion_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.Funcion#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference list.
   * The list contents are of type {@link upb.lp.edu.madonna.Param}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference list.
   * @see upb.lp.edu.madonna.MadonnaPackage#getFuncion_Param()
   * @model containment="true"
   * @generated
   */
  EList<Param> getParam();

  /**
   * Returns the value of the '<em><b>Declar</b></em>' containment reference list.
   * The list contents are of type {@link upb.lp.edu.madonna.Declaracion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declar</em>' containment reference list.
   * @see upb.lp.edu.madonna.MadonnaPackage#getFuncion_Declar()
   * @model containment="true"
   * @generated
   */
  EList<Declaracion> getDeclar();

  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(Valor)
   * @see upb.lp.edu.madonna.MadonnaPackage#getFuncion_Val()
   * @model containment="true"
   * @generated
   */
  Valor getVal();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.Funcion#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(Valor value);

} // Funcion
