/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instrucciones</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getInstrucciones()
 * @model
 * @generated
 */
public interface Instrucciones extends EObject
{
} // Instrucciones
