/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Llamado Func</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.LlamadoFunc#getFuncionID <em>Funcion ID</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.LlamadoFunc#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getLlamadoFunc()
 * @model
 * @generated
 */
public interface LlamadoFunc extends Expresion
{
  /**
   * Returns the value of the '<em><b>Funcion ID</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Funcion ID</em>' reference.
   * @see #setFuncionID(Declaracion)
   * @see upb.lp.edu.madonna.MadonnaPackage#getLlamadoFunc_FuncionID()
   * @model
   * @generated
   */
  Declaracion getFuncionID();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.LlamadoFunc#getFuncionID <em>Funcion ID</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Funcion ID</em>' reference.
   * @see #getFuncionID()
   * @generated
   */
  void setFuncionID(Declaracion value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link upb.lp.edu.madonna.Valor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see upb.lp.edu.madonna.MadonnaPackage#getLlamadoFunc_Args()
   * @model containment="true"
   * @generated
   */
  EList<Valor> getArgs();

} // LlamadoFunc
