/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see upb.lp.edu.madonna.MadonnaFactory
 * @model kind="package"
 * @generated
 */
public interface MadonnaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "madonna";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.lp.upb/edu/Madonna";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "madonna";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MadonnaPackage eINSTANCE = upb.lp.edu.madonna.impl.MadonnaPackageImpl.init();

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ProgramaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__NAME = 0;

  /**
   * The feature id for the '<em><b>Prog</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__PROG = 1;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.InstruccionesImpl <em>Instrucciones</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.InstruccionesImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getInstrucciones()
   * @generated
   */
  int INSTRUCCIONES = 2;

  /**
   * The number of structural features of the '<em>Instrucciones</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCIONES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.DeclaracionImpl <em>Declaracion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.DeclaracionImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getDeclaracion()
   * @generated
   */
  int DECLARACION = 5;

  /**
   * The number of structural features of the '<em>Declaracion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACION_FEATURE_COUNT = INSTRUCCIONES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.PrintImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 1;

  /**
   * The feature id for the '<em><b>Print Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__PRINT_TIPO = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__VAL = DECLARACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ValorImpl <em>Valor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ValorImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getValor()
   * @generated
   */
  int VALOR = 13;

  /**
   * The number of structural features of the '<em>Valor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALOR_FEATURE_COUNT = INSTRUCCIONES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ExpresionImpl <em>Expresion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ExpresionImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExpresion()
   * @generated
   */
  int EXPRESION = 14;

  /**
   * The number of structural features of the '<em>Expresion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESION_FEATURE_COUNT = VALOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.LlaveImpl <em>Llave</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.LlaveImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getLlave()
   * @generated
   */
  int LLAVE = 3;

  /**
   * The feature id for the '<em><b>Expr Log Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE__EXPR_LOG_CONDICION = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Acorde Res</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE__ACORDE_RES = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rep</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE__REP = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Llave</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAVE_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.LlamadoFuncImpl <em>Llamado Func</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.LlamadoFuncImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getLlamadoFunc()
   * @generated
   */
  int LLAMADO_FUNC = 4;

  /**
   * The feature id for the '<em><b>Funcion ID</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAMADO_FUNC__FUNCION_ID = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAMADO_FUNC__ARGS = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Llamado Func</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LLAMADO_FUNC_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.FuncionImpl <em>Funcion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.FuncionImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getFuncion()
   * @generated
   */
  int FUNCION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__NAME = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__PARAM = DECLARACION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Declar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__DECLAR = DECLARACION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION__VAL = DECLARACION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Funcion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCION_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.AsignacionNotaImpl <em>Asignacion Nota</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.AsignacionNotaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionNota()
   * @generated
   */
  int ASIGNACION_NOTA = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_NOTA__NAME = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_NOTA__VAL = DECLARACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Asignacion Nota</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_NOTA_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.AsignacionMelodiaImpl <em>Asignacion Melodia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.AsignacionMelodiaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionMelodia()
   * @generated
   */
  int ASIGNACION_MELODIA = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_MELODIA__NAME = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_MELODIA__VAL = DECLARACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Asignacion Melodia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_MELODIA_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.AsignacionSubNotaImpl <em>Asignacion Sub Nota</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.AsignacionSubNotaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionSubNota()
   * @generated
   */
  int ASIGNACION_SUB_NOTA = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_SUB_NOTA__NAME = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_SUB_NOTA__VAL = DECLARACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Asignacion Sub Nota</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_SUB_NOTA_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.AsignacionRitmoImpl <em>Asignacion Ritmo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.AsignacionRitmoImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionRitmo()
   * @generated
   */
  int ASIGNACION_RITMO = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_RITMO__NAME = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_RITMO__VAL = DECLARACION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Asignacion Ritmo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASIGNACION_RITMO_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ParamImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getParam()
   * @generated
   */
  int PARAM = 11;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = DECLARACION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ConstanteImpl <em>Constante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ConstanteImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getConstante()
   * @generated
   */
  int CONSTANTE = 12;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE__NOMBRE = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ExprConcatenacionImpl <em>Expr Concatenacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ExprConcatenacionImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprConcatenacion()
   * @generated
   */
  int EXPR_CONCATENACION = 15;

  /**
   * The feature id for the '<em><b>Operador Con</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION__OPERADOR_CON = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Con</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION__EXPR_CON = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Concatenacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_CONCATENACION_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ExprAritmeticaImpl <em>Expr Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ExprAritmeticaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprAritmetica()
   * @generated
   */
  int EXPR_ARITMETICA = 16;

  /**
   * The feature id for the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_ARITMETICA__OPERADOR_AR = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Ar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_ARITMETICA__EXPR_AR = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_ARITMETICA_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ExprLogicaImpl <em>Expr Logica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ExprLogicaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprLogica()
   * @generated
   */
  int EXPR_LOGICA = 17;

  /**
   * The feature id for the '<em><b>Negado</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA__NEGADO = EXPRESION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr Log</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA__EXPR_LOG = EXPRESION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expr Logica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA_FEATURE_COUNT = EXPRESION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ExprLogicaOperadoresImpl <em>Expr Logica Operadores</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ExprLogicaOperadoresImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprLogicaOperadores()
   * @generated
   */
  int EXPR_LOGICA_OPERADORES = 18;

  /**
   * The feature id for the '<em><b>Operador Log</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA_OPERADORES__OPERADOR_LOG = 0;

  /**
   * The feature id for the '<em><b>Expr Logs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA_OPERADORES__EXPR_LOGS = 1;

  /**
   * The number of structural features of the '<em>Expr Logica Operadores</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_LOGICA_OPERADORES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.ExprComparacionImpl <em>Expr Comparacion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.ExprComparacionImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprComparacion()
   * @generated
   */
  int EXPR_COMPARACION = 19;

  /**
   * The feature id for the '<em><b>Operador Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__OPERADOR_COMP = 0;

  /**
   * The feature id for the '<em><b>Expr Com Izq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__EXPR_COM_IZQ = 1;

  /**
   * The feature id for the '<em><b>Expr Com Der</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION__EXPR_COM_DER = 2;

  /**
   * The number of structural features of the '<em>Expr Comparacion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_COMPARACION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.PrimitivoImpl <em>Primitivo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.PrimitivoImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getPrimitivo()
   * @generated
   */
  int PRIMITIVO = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVO__NAME = PARAM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVO__TIPO = PARAM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Primitivo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVO_FEATURE_COUNT = PARAM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.NotaImpl <em>Nota</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.NotaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getNota()
   * @generated
   */
  int NOTA = 21;

  /**
   * The feature id for the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTA__OPERADOR_AR = EXPR_ARITMETICA__OPERADOR_AR;

  /**
   * The feature id for the '<em><b>Expr Ar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTA__EXPR_AR = EXPR_ARITMETICA__EXPR_AR;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTA__X = EXPR_ARITMETICA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Nota</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTA_FEATURE_COUNT = EXPR_ARITMETICA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.MelodiaImpl <em>Melodia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.MelodiaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getMelodia()
   * @generated
   */
  int MELODIA = 22;

  /**
   * The feature id for the '<em><b>Operador Con</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MELODIA__OPERADOR_CON = EXPR_CONCATENACION__OPERADOR_CON;

  /**
   * The feature id for the '<em><b>Expr Con</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MELODIA__EXPR_CON = EXPR_CONCATENACION__EXPR_CON;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MELODIA__X = EXPR_CONCATENACION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Melodia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MELODIA_FEATURE_COUNT = EXPR_CONCATENACION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.SubNotaImpl <em>Sub Nota</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.SubNotaImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getSubNota()
   * @generated
   */
  int SUB_NOTA = 23;

  /**
   * The feature id for the '<em><b>Operador Ar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_NOTA__OPERADOR_AR = EXPR_ARITMETICA__OPERADOR_AR;

  /**
   * The feature id for the '<em><b>Expr Ar</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_NOTA__EXPR_AR = EXPR_ARITMETICA__EXPR_AR;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_NOTA__X = EXPR_ARITMETICA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sub Nota</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_NOTA_FEATURE_COUNT = EXPR_ARITMETICA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link upb.lp.edu.madonna.impl.RitmoImpl <em>Ritmo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see upb.lp.edu.madonna.impl.RitmoImpl
   * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getRitmo()
   * @generated
   */
  int RITMO = 24;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RITMO__X = 0;

  /**
   * The number of structural features of the '<em>Ritmo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RITMO_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see upb.lp.edu.madonna.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Programa#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.Programa#getName()
   * @see #getPrograma()
   * @generated
   */
  EAttribute getPrograma_Name();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.Programa#getProg <em>Prog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prog</em>'.
   * @see upb.lp.edu.madonna.Programa#getProg()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Prog();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see upb.lp.edu.madonna.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Print#getPrintTipo <em>Print Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Print Tipo</em>'.
   * @see upb.lp.edu.madonna.Print#getPrintTipo()
   * @see #getPrint()
   * @generated
   */
  EAttribute getPrint_PrintTipo();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.Print#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see upb.lp.edu.madonna.Print#getVal()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Val();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Instrucciones <em>Instrucciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instrucciones</em>'.
   * @see upb.lp.edu.madonna.Instrucciones
   * @generated
   */
  EClass getInstrucciones();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Llave <em>Llave</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Llave</em>'.
   * @see upb.lp.edu.madonna.Llave
   * @generated
   */
  EClass getLlave();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.Llave#getExprLogCondicion <em>Expr Log Condicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Log Condicion</em>'.
   * @see upb.lp.edu.madonna.Llave#getExprLogCondicion()
   * @see #getLlave()
   * @generated
   */
  EReference getLlave_ExprLogCondicion();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.Llave#getAcordeRes <em>Acorde Res</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Acorde Res</em>'.
   * @see upb.lp.edu.madonna.Llave#getAcordeRes()
   * @see #getLlave()
   * @generated
   */
  EReference getLlave_AcordeRes();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.Llave#getRep <em>Rep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rep</em>'.
   * @see upb.lp.edu.madonna.Llave#getRep()
   * @see #getLlave()
   * @generated
   */
  EReference getLlave_Rep();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.LlamadoFunc <em>Llamado Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Llamado Func</em>'.
   * @see upb.lp.edu.madonna.LlamadoFunc
   * @generated
   */
  EClass getLlamadoFunc();

  /**
   * Returns the meta object for the reference '{@link upb.lp.edu.madonna.LlamadoFunc#getFuncionID <em>Funcion ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Funcion ID</em>'.
   * @see upb.lp.edu.madonna.LlamadoFunc#getFuncionID()
   * @see #getLlamadoFunc()
   * @generated
   */
  EReference getLlamadoFunc_FuncionID();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.LlamadoFunc#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see upb.lp.edu.madonna.LlamadoFunc#getArgs()
   * @see #getLlamadoFunc()
   * @generated
   */
  EReference getLlamadoFunc_Args();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Declaracion <em>Declaracion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaracion</em>'.
   * @see upb.lp.edu.madonna.Declaracion
   * @generated
   */
  EClass getDeclaracion();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Funcion <em>Funcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Funcion</em>'.
   * @see upb.lp.edu.madonna.Funcion
   * @generated
   */
  EClass getFuncion();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Funcion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.Funcion#getName()
   * @see #getFuncion()
   * @generated
   */
  EAttribute getFuncion_Name();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.Funcion#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see upb.lp.edu.madonna.Funcion#getParam()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Param();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.Funcion#getDeclar <em>Declar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declar</em>'.
   * @see upb.lp.edu.madonna.Funcion#getDeclar()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Declar();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.Funcion#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see upb.lp.edu.madonna.Funcion#getVal()
   * @see #getFuncion()
   * @generated
   */
  EReference getFuncion_Val();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.AsignacionNota <em>Asignacion Nota</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asignacion Nota</em>'.
   * @see upb.lp.edu.madonna.AsignacionNota
   * @generated
   */
  EClass getAsignacionNota();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.AsignacionNota#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.AsignacionNota#getName()
   * @see #getAsignacionNota()
   * @generated
   */
  EAttribute getAsignacionNota_Name();

  /**
   * Returns the meta object for the reference '{@link upb.lp.edu.madonna.AsignacionNota#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Val</em>'.
   * @see upb.lp.edu.madonna.AsignacionNota#getVal()
   * @see #getAsignacionNota()
   * @generated
   */
  EReference getAsignacionNota_Val();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.AsignacionMelodia <em>Asignacion Melodia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asignacion Melodia</em>'.
   * @see upb.lp.edu.madonna.AsignacionMelodia
   * @generated
   */
  EClass getAsignacionMelodia();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.AsignacionMelodia#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.AsignacionMelodia#getName()
   * @see #getAsignacionMelodia()
   * @generated
   */
  EAttribute getAsignacionMelodia_Name();

  /**
   * Returns the meta object for the reference '{@link upb.lp.edu.madonna.AsignacionMelodia#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Val</em>'.
   * @see upb.lp.edu.madonna.AsignacionMelodia#getVal()
   * @see #getAsignacionMelodia()
   * @generated
   */
  EReference getAsignacionMelodia_Val();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.AsignacionSubNota <em>Asignacion Sub Nota</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asignacion Sub Nota</em>'.
   * @see upb.lp.edu.madonna.AsignacionSubNota
   * @generated
   */
  EClass getAsignacionSubNota();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.AsignacionSubNota#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.AsignacionSubNota#getName()
   * @see #getAsignacionSubNota()
   * @generated
   */
  EAttribute getAsignacionSubNota_Name();

  /**
   * Returns the meta object for the reference '{@link upb.lp.edu.madonna.AsignacionSubNota#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Val</em>'.
   * @see upb.lp.edu.madonna.AsignacionSubNota#getVal()
   * @see #getAsignacionSubNota()
   * @generated
   */
  EReference getAsignacionSubNota_Val();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.AsignacionRitmo <em>Asignacion Ritmo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asignacion Ritmo</em>'.
   * @see upb.lp.edu.madonna.AsignacionRitmo
   * @generated
   */
  EClass getAsignacionRitmo();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.AsignacionRitmo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.AsignacionRitmo#getName()
   * @see #getAsignacionRitmo()
   * @generated
   */
  EAttribute getAsignacionRitmo_Name();

  /**
   * Returns the meta object for the reference '{@link upb.lp.edu.madonna.AsignacionRitmo#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Val</em>'.
   * @see upb.lp.edu.madonna.AsignacionRitmo#getVal()
   * @see #getAsignacionRitmo()
   * @generated
   */
  EReference getAsignacionRitmo_Val();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see upb.lp.edu.madonna.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Constante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante</em>'.
   * @see upb.lp.edu.madonna.Constante
   * @generated
   */
  EClass getConstante();

  /**
   * Returns the meta object for the reference '{@link upb.lp.edu.madonna.Constante#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Nombre</em>'.
   * @see upb.lp.edu.madonna.Constante#getNombre()
   * @see #getConstante()
   * @generated
   */
  EReference getConstante_Nombre();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Valor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Valor</em>'.
   * @see upb.lp.edu.madonna.Valor
   * @generated
   */
  EClass getValor();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expresion</em>'.
   * @see upb.lp.edu.madonna.Expresion
   * @generated
   */
  EClass getExpresion();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.ExprConcatenacion <em>Expr Concatenacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Concatenacion</em>'.
   * @see upb.lp.edu.madonna.ExprConcatenacion
   * @generated
   */
  EClass getExprConcatenacion();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.ExprConcatenacion#getOperadorCon <em>Operador Con</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Con</em>'.
   * @see upb.lp.edu.madonna.ExprConcatenacion#getOperadorCon()
   * @see #getExprConcatenacion()
   * @generated
   */
  EAttribute getExprConcatenacion_OperadorCon();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.ExprConcatenacion#getExprCon <em>Expr Con</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr Con</em>'.
   * @see upb.lp.edu.madonna.ExprConcatenacion#getExprCon()
   * @see #getExprConcatenacion()
   * @generated
   */
  EReference getExprConcatenacion_ExprCon();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.ExprAritmetica <em>Expr Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Aritmetica</em>'.
   * @see upb.lp.edu.madonna.ExprAritmetica
   * @generated
   */
  EClass getExprAritmetica();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.ExprAritmetica#getOperadorAr <em>Operador Ar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Ar</em>'.
   * @see upb.lp.edu.madonna.ExprAritmetica#getOperadorAr()
   * @see #getExprAritmetica()
   * @generated
   */
  EAttribute getExprAritmetica_OperadorAr();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.ExprAritmetica#getExprAr <em>Expr Ar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr Ar</em>'.
   * @see upb.lp.edu.madonna.ExprAritmetica#getExprAr()
   * @see #getExprAritmetica()
   * @generated
   */
  EReference getExprAritmetica_ExprAr();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.ExprLogica <em>Expr Logica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Logica</em>'.
   * @see upb.lp.edu.madonna.ExprLogica
   * @generated
   */
  EClass getExprLogica();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.ExprLogica#isNegado <em>Negado</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negado</em>'.
   * @see upb.lp.edu.madonna.ExprLogica#isNegado()
   * @see #getExprLogica()
   * @generated
   */
  EAttribute getExprLogica_Negado();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.ExprLogica#getExprLog <em>Expr Log</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Log</em>'.
   * @see upb.lp.edu.madonna.ExprLogica#getExprLog()
   * @see #getExprLogica()
   * @generated
   */
  EReference getExprLogica_ExprLog();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.ExprLogicaOperadores <em>Expr Logica Operadores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Logica Operadores</em>'.
   * @see upb.lp.edu.madonna.ExprLogicaOperadores
   * @generated
   */
  EClass getExprLogicaOperadores();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.ExprLogicaOperadores#getOperadorLog <em>Operador Log</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Log</em>'.
   * @see upb.lp.edu.madonna.ExprLogicaOperadores#getOperadorLog()
   * @see #getExprLogicaOperadores()
   * @generated
   */
  EAttribute getExprLogicaOperadores_OperadorLog();

  /**
   * Returns the meta object for the containment reference list '{@link upb.lp.edu.madonna.ExprLogicaOperadores#getExprLogs <em>Expr Logs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr Logs</em>'.
   * @see upb.lp.edu.madonna.ExprLogicaOperadores#getExprLogs()
   * @see #getExprLogicaOperadores()
   * @generated
   */
  EReference getExprLogicaOperadores_ExprLogs();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.ExprComparacion <em>Expr Comparacion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Comparacion</em>'.
   * @see upb.lp.edu.madonna.ExprComparacion
   * @generated
   */
  EClass getExprComparacion();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.ExprComparacion#getOperadorComp <em>Operador Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador Comp</em>'.
   * @see upb.lp.edu.madonna.ExprComparacion#getOperadorComp()
   * @see #getExprComparacion()
   * @generated
   */
  EAttribute getExprComparacion_OperadorComp();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.ExprComparacion#getExprComIzq <em>Expr Com Izq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Com Izq</em>'.
   * @see upb.lp.edu.madonna.ExprComparacion#getExprComIzq()
   * @see #getExprComparacion()
   * @generated
   */
  EReference getExprComparacion_ExprComIzq();

  /**
   * Returns the meta object for the containment reference '{@link upb.lp.edu.madonna.ExprComparacion#getExprComDer <em>Expr Com Der</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr Com Der</em>'.
   * @see upb.lp.edu.madonna.ExprComparacion#getExprComDer()
   * @see #getExprComparacion()
   * @generated
   */
  EReference getExprComparacion_ExprComDer();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Primitivo <em>Primitivo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitivo</em>'.
   * @see upb.lp.edu.madonna.Primitivo
   * @generated
   */
  EClass getPrimitivo();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Primitivo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see upb.lp.edu.madonna.Primitivo#getName()
   * @see #getPrimitivo()
   * @generated
   */
  EAttribute getPrimitivo_Name();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Primitivo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see upb.lp.edu.madonna.Primitivo#getTipo()
   * @see #getPrimitivo()
   * @generated
   */
  EAttribute getPrimitivo_Tipo();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Nota <em>Nota</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nota</em>'.
   * @see upb.lp.edu.madonna.Nota
   * @generated
   */
  EClass getNota();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Nota#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see upb.lp.edu.madonna.Nota#getX()
   * @see #getNota()
   * @generated
   */
  EAttribute getNota_X();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Melodia <em>Melodia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Melodia</em>'.
   * @see upb.lp.edu.madonna.Melodia
   * @generated
   */
  EClass getMelodia();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Melodia#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see upb.lp.edu.madonna.Melodia#getX()
   * @see #getMelodia()
   * @generated
   */
  EAttribute getMelodia_X();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.SubNota <em>Sub Nota</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Nota</em>'.
   * @see upb.lp.edu.madonna.SubNota
   * @generated
   */
  EClass getSubNota();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.SubNota#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see upb.lp.edu.madonna.SubNota#getX()
   * @see #getSubNota()
   * @generated
   */
  EAttribute getSubNota_X();

  /**
   * Returns the meta object for class '{@link upb.lp.edu.madonna.Ritmo <em>Ritmo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ritmo</em>'.
   * @see upb.lp.edu.madonna.Ritmo
   * @generated
   */
  EClass getRitmo();

  /**
   * Returns the meta object for the attribute '{@link upb.lp.edu.madonna.Ritmo#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see upb.lp.edu.madonna.Ritmo#getX()
   * @see #getRitmo()
   * @generated
   */
  EAttribute getRitmo_X();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MadonnaFactory getMadonnaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ProgramaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAMA__NAME = eINSTANCE.getPrograma_Name();

    /**
     * The meta object literal for the '<em><b>Prog</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__PROG = eINSTANCE.getPrograma_Prog();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.PrintImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Print Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRINT__PRINT_TIPO = eINSTANCE.getPrint_PrintTipo();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__VAL = eINSTANCE.getPrint_Val();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.InstruccionesImpl <em>Instrucciones</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.InstruccionesImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getInstrucciones()
     * @generated
     */
    EClass INSTRUCCIONES = eINSTANCE.getInstrucciones();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.LlaveImpl <em>Llave</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.LlaveImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getLlave()
     * @generated
     */
    EClass LLAVE = eINSTANCE.getLlave();

    /**
     * The meta object literal for the '<em><b>Expr Log Condicion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAVE__EXPR_LOG_CONDICION = eINSTANCE.getLlave_ExprLogCondicion();

    /**
     * The meta object literal for the '<em><b>Acorde Res</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAVE__ACORDE_RES = eINSTANCE.getLlave_AcordeRes();

    /**
     * The meta object literal for the '<em><b>Rep</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAVE__REP = eINSTANCE.getLlave_Rep();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.LlamadoFuncImpl <em>Llamado Func</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.LlamadoFuncImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getLlamadoFunc()
     * @generated
     */
    EClass LLAMADO_FUNC = eINSTANCE.getLlamadoFunc();

    /**
     * The meta object literal for the '<em><b>Funcion ID</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAMADO_FUNC__FUNCION_ID = eINSTANCE.getLlamadoFunc_FuncionID();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LLAMADO_FUNC__ARGS = eINSTANCE.getLlamadoFunc_Args();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.DeclaracionImpl <em>Declaracion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.DeclaracionImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getDeclaracion()
     * @generated
     */
    EClass DECLARACION = eINSTANCE.getDeclaracion();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.FuncionImpl <em>Funcion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.FuncionImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getFuncion()
     * @generated
     */
    EClass FUNCION = eINSTANCE.getFuncion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCION__NAME = eINSTANCE.getFuncion_Name();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__PARAM = eINSTANCE.getFuncion_Param();

    /**
     * The meta object literal for the '<em><b>Declar</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__DECLAR = eINSTANCE.getFuncion_Declar();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCION__VAL = eINSTANCE.getFuncion_Val();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.AsignacionNotaImpl <em>Asignacion Nota</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.AsignacionNotaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionNota()
     * @generated
     */
    EClass ASIGNACION_NOTA = eINSTANCE.getAsignacionNota();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASIGNACION_NOTA__NAME = eINSTANCE.getAsignacionNota_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASIGNACION_NOTA__VAL = eINSTANCE.getAsignacionNota_Val();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.AsignacionMelodiaImpl <em>Asignacion Melodia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.AsignacionMelodiaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionMelodia()
     * @generated
     */
    EClass ASIGNACION_MELODIA = eINSTANCE.getAsignacionMelodia();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASIGNACION_MELODIA__NAME = eINSTANCE.getAsignacionMelodia_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASIGNACION_MELODIA__VAL = eINSTANCE.getAsignacionMelodia_Val();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.AsignacionSubNotaImpl <em>Asignacion Sub Nota</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.AsignacionSubNotaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionSubNota()
     * @generated
     */
    EClass ASIGNACION_SUB_NOTA = eINSTANCE.getAsignacionSubNota();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASIGNACION_SUB_NOTA__NAME = eINSTANCE.getAsignacionSubNota_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASIGNACION_SUB_NOTA__VAL = eINSTANCE.getAsignacionSubNota_Val();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.AsignacionRitmoImpl <em>Asignacion Ritmo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.AsignacionRitmoImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getAsignacionRitmo()
     * @generated
     */
    EClass ASIGNACION_RITMO = eINSTANCE.getAsignacionRitmo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASIGNACION_RITMO__NAME = eINSTANCE.getAsignacionRitmo_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASIGNACION_RITMO__VAL = eINSTANCE.getAsignacionRitmo_Val();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ParamImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ConstanteImpl <em>Constante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ConstanteImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getConstante()
     * @generated
     */
    EClass CONSTANTE = eINSTANCE.getConstante();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANTE__NOMBRE = eINSTANCE.getConstante_Nombre();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ValorImpl <em>Valor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ValorImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getValor()
     * @generated
     */
    EClass VALOR = eINSTANCE.getValor();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ExpresionImpl <em>Expresion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ExpresionImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExpresion()
     * @generated
     */
    EClass EXPRESION = eINSTANCE.getExpresion();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ExprConcatenacionImpl <em>Expr Concatenacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ExprConcatenacionImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprConcatenacion()
     * @generated
     */
    EClass EXPR_CONCATENACION = eINSTANCE.getExprConcatenacion();

    /**
     * The meta object literal for the '<em><b>Operador Con</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_CONCATENACION__OPERADOR_CON = eINSTANCE.getExprConcatenacion_OperadorCon();

    /**
     * The meta object literal for the '<em><b>Expr Con</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_CONCATENACION__EXPR_CON = eINSTANCE.getExprConcatenacion_ExprCon();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ExprAritmeticaImpl <em>Expr Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ExprAritmeticaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprAritmetica()
     * @generated
     */
    EClass EXPR_ARITMETICA = eINSTANCE.getExprAritmetica();

    /**
     * The meta object literal for the '<em><b>Operador Ar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_ARITMETICA__OPERADOR_AR = eINSTANCE.getExprAritmetica_OperadorAr();

    /**
     * The meta object literal for the '<em><b>Expr Ar</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_ARITMETICA__EXPR_AR = eINSTANCE.getExprAritmetica_ExprAr();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ExprLogicaImpl <em>Expr Logica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ExprLogicaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprLogica()
     * @generated
     */
    EClass EXPR_LOGICA = eINSTANCE.getExprLogica();

    /**
     * The meta object literal for the '<em><b>Negado</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_LOGICA__NEGADO = eINSTANCE.getExprLogica_Negado();

    /**
     * The meta object literal for the '<em><b>Expr Log</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_LOGICA__EXPR_LOG = eINSTANCE.getExprLogica_ExprLog();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ExprLogicaOperadoresImpl <em>Expr Logica Operadores</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ExprLogicaOperadoresImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprLogicaOperadores()
     * @generated
     */
    EClass EXPR_LOGICA_OPERADORES = eINSTANCE.getExprLogicaOperadores();

    /**
     * The meta object literal for the '<em><b>Operador Log</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_LOGICA_OPERADORES__OPERADOR_LOG = eINSTANCE.getExprLogicaOperadores_OperadorLog();

    /**
     * The meta object literal for the '<em><b>Expr Logs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_LOGICA_OPERADORES__EXPR_LOGS = eINSTANCE.getExprLogicaOperadores_ExprLogs();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.ExprComparacionImpl <em>Expr Comparacion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.ExprComparacionImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getExprComparacion()
     * @generated
     */
    EClass EXPR_COMPARACION = eINSTANCE.getExprComparacion();

    /**
     * The meta object literal for the '<em><b>Operador Comp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_COMPARACION__OPERADOR_COMP = eINSTANCE.getExprComparacion_OperadorComp();

    /**
     * The meta object literal for the '<em><b>Expr Com Izq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_COMPARACION__EXPR_COM_IZQ = eINSTANCE.getExprComparacion_ExprComIzq();

    /**
     * The meta object literal for the '<em><b>Expr Com Der</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_COMPARACION__EXPR_COM_DER = eINSTANCE.getExprComparacion_ExprComDer();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.PrimitivoImpl <em>Primitivo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.PrimitivoImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getPrimitivo()
     * @generated
     */
    EClass PRIMITIVO = eINSTANCE.getPrimitivo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMITIVO__NAME = eINSTANCE.getPrimitivo_Name();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMITIVO__TIPO = eINSTANCE.getPrimitivo_Tipo();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.NotaImpl <em>Nota</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.NotaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getNota()
     * @generated
     */
    EClass NOTA = eINSTANCE.getNota();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTA__X = eINSTANCE.getNota_X();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.MelodiaImpl <em>Melodia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.MelodiaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getMelodia()
     * @generated
     */
    EClass MELODIA = eINSTANCE.getMelodia();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MELODIA__X = eINSTANCE.getMelodia_X();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.SubNotaImpl <em>Sub Nota</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.SubNotaImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getSubNota()
     * @generated
     */
    EClass SUB_NOTA = eINSTANCE.getSubNota();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_NOTA__X = eINSTANCE.getSubNota_X();

    /**
     * The meta object literal for the '{@link upb.lp.edu.madonna.impl.RitmoImpl <em>Ritmo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see upb.lp.edu.madonna.impl.RitmoImpl
     * @see upb.lp.edu.madonna.impl.MadonnaPackageImpl#getRitmo()
     * @generated
     */
    EClass RITMO = eINSTANCE.getRitmo();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RITMO__X = eINSTANCE.getRitmo_X();

  }

} //MadonnaPackage
