/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see upb.lp.edu.madonna.MadonnaPackage
 * @generated
 */
public interface MadonnaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MadonnaFactory eINSTANCE = upb.lp.edu.madonna.impl.MadonnaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Programa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Programa</em>'.
   * @generated
   */
  Programa createPrograma();

  /**
   * Returns a new object of class '<em>Print</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print</em>'.
   * @generated
   */
  Print createPrint();

  /**
   * Returns a new object of class '<em>Instrucciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instrucciones</em>'.
   * @generated
   */
  Instrucciones createInstrucciones();

  /**
   * Returns a new object of class '<em>Llave</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llave</em>'.
   * @generated
   */
  Llave createLlave();

  /**
   * Returns a new object of class '<em>Llamado Func</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llamado Func</em>'.
   * @generated
   */
  LlamadoFunc createLlamadoFunc();

  /**
   * Returns a new object of class '<em>Declaracion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaracion</em>'.
   * @generated
   */
  Declaracion createDeclaracion();

  /**
   * Returns a new object of class '<em>Funcion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Funcion</em>'.
   * @generated
   */
  Funcion createFuncion();

  /**
   * Returns a new object of class '<em>Asignacion Nota</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asignacion Nota</em>'.
   * @generated
   */
  AsignacionNota createAsignacionNota();

  /**
   * Returns a new object of class '<em>Asignacion Melodia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asignacion Melodia</em>'.
   * @generated
   */
  AsignacionMelodia createAsignacionMelodia();

  /**
   * Returns a new object of class '<em>Asignacion Sub Nota</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asignacion Sub Nota</em>'.
   * @generated
   */
  AsignacionSubNota createAsignacionSubNota();

  /**
   * Returns a new object of class '<em>Asignacion Ritmo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asignacion Ritmo</em>'.
   * @generated
   */
  AsignacionRitmo createAsignacionRitmo();

  /**
   * Returns a new object of class '<em>Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Param</em>'.
   * @generated
   */
  Param createParam();

  /**
   * Returns a new object of class '<em>Constante</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante</em>'.
   * @generated
   */
  Constante createConstante();

  /**
   * Returns a new object of class '<em>Valor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valor</em>'.
   * @generated
   */
  Valor createValor();

  /**
   * Returns a new object of class '<em>Expresion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expresion</em>'.
   * @generated
   */
  Expresion createExpresion();

  /**
   * Returns a new object of class '<em>Expr Concatenacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Concatenacion</em>'.
   * @generated
   */
  ExprConcatenacion createExprConcatenacion();

  /**
   * Returns a new object of class '<em>Expr Aritmetica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Aritmetica</em>'.
   * @generated
   */
  ExprAritmetica createExprAritmetica();

  /**
   * Returns a new object of class '<em>Expr Logica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Logica</em>'.
   * @generated
   */
  ExprLogica createExprLogica();

  /**
   * Returns a new object of class '<em>Expr Logica Operadores</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Logica Operadores</em>'.
   * @generated
   */
  ExprLogicaOperadores createExprLogicaOperadores();

  /**
   * Returns a new object of class '<em>Expr Comparacion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expr Comparacion</em>'.
   * @generated
   */
  ExprComparacion createExprComparacion();

  /**
   * Returns a new object of class '<em>Primitivo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitivo</em>'.
   * @generated
   */
  Primitivo createPrimitivo();

  /**
   * Returns a new object of class '<em>Nota</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nota</em>'.
   * @generated
   */
  Nota createNota();

  /**
   * Returns a new object of class '<em>Melodia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Melodia</em>'.
   * @generated
   */
  Melodia createMelodia();

  /**
   * Returns a new object of class '<em>Sub Nota</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Nota</em>'.
   * @generated
   */
  SubNota createSubNota();

  /**
   * Returns a new object of class '<em>Ritmo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ritmo</em>'.
   * @generated
   */
  Ritmo createRitmo();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MadonnaPackage getMadonnaPackage();

} //MadonnaFactory
