/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getParam()
 * @model
 * @generated
 */
public interface Param extends Declaracion
{
} // Param
