/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.Print#getPrintTipo <em>Print Tipo</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.Print#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getPrint()
 * @model
 * @generated
 */
public interface Print extends Declaracion
{
  /**
   * Returns the value of the '<em><b>Print Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Print Tipo</em>' attribute.
   * @see #setPrintTipo(String)
   * @see upb.lp.edu.madonna.MadonnaPackage#getPrint_PrintTipo()
   * @model
   * @generated
   */
  String getPrintTipo();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.Print#getPrintTipo <em>Print Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Print Tipo</em>' attribute.
   * @see #getPrintTipo()
   * @generated
   */
  void setPrintTipo(String value);

  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(Valor)
   * @see upb.lp.edu.madonna.MadonnaPackage#getPrint_Val()
   * @model containment="true"
   * @generated
   */
  Valor getVal();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.Print#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(Valor value);

} // Print
