/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Nota</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.SubNota#getX <em>X</em>}</li>
 * </ul>
 *
 * @see upb.lp.edu.madonna.MadonnaPackage#getSubNota()
 * @model
 * @generated
 */
public interface SubNota extends ExprAritmetica
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(double)
   * @see upb.lp.edu.madonna.MadonnaPackage#getSubNota_X()
   * @model
   * @generated
   */
  double getX();

  /**
   * Sets the value of the '{@link upb.lp.edu.madonna.SubNota#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(double value);

} // SubNota
