/*
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.ui.tests;

import com.google.inject.Injector;
import madonna.ui.internal.MadonnaActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MadonnaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MadonnaActivator.getInstance().getInjector("upb.lp.edu.Madonna");
	}

}
