/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import org.eclipse.emf.ecore.EClass;

import upb.lp.edu.madonna.Declaracion;
import upb.lp.edu.madonna.MadonnaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declaracion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeclaracionImpl extends InstruccionesImpl implements Declaracion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclaracionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MadonnaPackage.Literals.DECLARACION;
  }

} //DeclaracionImpl
