/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import upb.lp.edu.madonna.ExprLogicaOperadores;
import upb.lp.edu.madonna.Expresion;
import upb.lp.edu.madonna.MadonnaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Logica Operadores</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.impl.ExprLogicaOperadoresImpl#getOperadorLog <em>Operador Log</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.impl.ExprLogicaOperadoresImpl#getExprLogs <em>Expr Logs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprLogicaOperadoresImpl extends MinimalEObjectImpl.Container implements ExprLogicaOperadores
{
  /**
   * The default value of the '{@link #getOperadorLog() <em>Operador Log</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperadorLog()
   * @generated
   * @ordered
   */
  protected static final String OPERADOR_LOG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperadorLog() <em>Operador Log</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperadorLog()
   * @generated
   * @ordered
   */
  protected String operadorLog = OPERADOR_LOG_EDEFAULT;

  /**
   * The cached value of the '{@link #getExprLogs() <em>Expr Logs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprLogs()
   * @generated
   * @ordered
   */
  protected EList<Expresion> exprLogs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprLogicaOperadoresImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MadonnaPackage.Literals.EXPR_LOGICA_OPERADORES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOperadorLog()
  {
    return operadorLog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperadorLog(String newOperadorLog)
  {
    String oldOperadorLog = operadorLog;
    operadorLog = newOperadorLog;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MadonnaPackage.EXPR_LOGICA_OPERADORES__OPERADOR_LOG, oldOperadorLog, operadorLog));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expresion> getExprLogs()
  {
    if (exprLogs == null)
    {
      exprLogs = new EObjectContainmentEList<Expresion>(Expresion.class, this, MadonnaPackage.EXPR_LOGICA_OPERADORES__EXPR_LOGS);
    }
    return exprLogs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__EXPR_LOGS:
        return ((InternalEList<?>)getExprLogs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__OPERADOR_LOG:
        return getOperadorLog();
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__EXPR_LOGS:
        return getExprLogs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__OPERADOR_LOG:
        setOperadorLog((String)newValue);
        return;
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__EXPR_LOGS:
        getExprLogs().clear();
        getExprLogs().addAll((Collection<? extends Expresion>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__OPERADOR_LOG:
        setOperadorLog(OPERADOR_LOG_EDEFAULT);
        return;
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__EXPR_LOGS:
        getExprLogs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__OPERADOR_LOG:
        return OPERADOR_LOG_EDEFAULT == null ? operadorLog != null : !OPERADOR_LOG_EDEFAULT.equals(operadorLog);
      case MadonnaPackage.EXPR_LOGICA_OPERADORES__EXPR_LOGS:
        return exprLogs != null && !exprLogs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operadorLog: ");
    result.append(operadorLog);
    result.append(')');
    return result.toString();
  }

} //ExprLogicaOperadoresImpl
