/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import upb.lp.edu.madonna.Instrucciones;
import upb.lp.edu.madonna.MadonnaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Instrucciones</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InstruccionesImpl extends MinimalEObjectImpl.Container implements Instrucciones
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InstruccionesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MadonnaPackage.Literals.INSTRUCCIONES;
  }

} //InstruccionesImpl
