/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import upb.lp.edu.madonna.Declaracion;
import upb.lp.edu.madonna.LlamadoFunc;
import upb.lp.edu.madonna.MadonnaPackage;
import upb.lp.edu.madonna.Valor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Llamado Func</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.impl.LlamadoFuncImpl#getFuncionID <em>Funcion ID</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.impl.LlamadoFuncImpl#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LlamadoFuncImpl extends ExpresionImpl implements LlamadoFunc
{
  /**
   * The cached value of the '{@link #getFuncionID() <em>Funcion ID</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuncionID()
   * @generated
   * @ordered
   */
  protected Declaracion funcionID;

  /**
   * The cached value of the '{@link #getArgs() <em>Args</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgs()
   * @generated
   * @ordered
   */
  protected EList<Valor> args;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LlamadoFuncImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MadonnaPackage.Literals.LLAMADO_FUNC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaracion getFuncionID()
  {
    if (funcionID != null && funcionID.eIsProxy())
    {
      InternalEObject oldFuncionID = (InternalEObject)funcionID;
      funcionID = (Declaracion)eResolveProxy(oldFuncionID);
      if (funcionID != oldFuncionID)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MadonnaPackage.LLAMADO_FUNC__FUNCION_ID, oldFuncionID, funcionID));
      }
    }
    return funcionID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Declaracion basicGetFuncionID()
  {
    return funcionID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFuncionID(Declaracion newFuncionID)
  {
    Declaracion oldFuncionID = funcionID;
    funcionID = newFuncionID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAMADO_FUNC__FUNCION_ID, oldFuncionID, funcionID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Valor> getArgs()
  {
    if (args == null)
    {
      args = new EObjectContainmentEList<Valor>(Valor.class, this, MadonnaPackage.LLAMADO_FUNC__ARGS);
    }
    return args;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAMADO_FUNC__ARGS:
        return ((InternalEList<?>)getArgs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAMADO_FUNC__FUNCION_ID:
        if (resolve) return getFuncionID();
        return basicGetFuncionID();
      case MadonnaPackage.LLAMADO_FUNC__ARGS:
        return getArgs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAMADO_FUNC__FUNCION_ID:
        setFuncionID((Declaracion)newValue);
        return;
      case MadonnaPackage.LLAMADO_FUNC__ARGS:
        getArgs().clear();
        getArgs().addAll((Collection<? extends Valor>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAMADO_FUNC__FUNCION_ID:
        setFuncionID((Declaracion)null);
        return;
      case MadonnaPackage.LLAMADO_FUNC__ARGS:
        getArgs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAMADO_FUNC__FUNCION_ID:
        return funcionID != null;
      case MadonnaPackage.LLAMADO_FUNC__ARGS:
        return args != null && !args.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LlamadoFuncImpl
