/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import upb.lp.edu.madonna.Expresion;
import upb.lp.edu.madonna.Llave;
import upb.lp.edu.madonna.MadonnaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Llave</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link upb.lp.edu.madonna.impl.LlaveImpl#getExprLogCondicion <em>Expr Log Condicion</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.impl.LlaveImpl#getAcordeRes <em>Acorde Res</em>}</li>
 *   <li>{@link upb.lp.edu.madonna.impl.LlaveImpl#getRep <em>Rep</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LlaveImpl extends ExpresionImpl implements Llave
{
  /**
   * The cached value of the '{@link #getExprLogCondicion() <em>Expr Log Condicion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprLogCondicion()
   * @generated
   * @ordered
   */
  protected Expresion exprLogCondicion;

  /**
   * The cached value of the '{@link #getAcordeRes() <em>Acorde Res</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAcordeRes()
   * @generated
   * @ordered
   */
  protected Expresion acordeRes;

  /**
   * The cached value of the '{@link #getRep() <em>Rep</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRep()
   * @generated
   * @ordered
   */
  protected Expresion rep;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LlaveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MadonnaPackage.Literals.LLAVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getExprLogCondicion()
  {
    return exprLogCondicion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprLogCondicion(Expresion newExprLogCondicion, NotificationChain msgs)
  {
    Expresion oldExprLogCondicion = exprLogCondicion;
    exprLogCondicion = newExprLogCondicion;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAVE__EXPR_LOG_CONDICION, oldExprLogCondicion, newExprLogCondicion);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExprLogCondicion(Expresion newExprLogCondicion)
  {
    if (newExprLogCondicion != exprLogCondicion)
    {
      NotificationChain msgs = null;
      if (exprLogCondicion != null)
        msgs = ((InternalEObject)exprLogCondicion).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MadonnaPackage.LLAVE__EXPR_LOG_CONDICION, null, msgs);
      if (newExprLogCondicion != null)
        msgs = ((InternalEObject)newExprLogCondicion).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MadonnaPackage.LLAVE__EXPR_LOG_CONDICION, null, msgs);
      msgs = basicSetExprLogCondicion(newExprLogCondicion, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAVE__EXPR_LOG_CONDICION, newExprLogCondicion, newExprLogCondicion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getAcordeRes()
  {
    return acordeRes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAcordeRes(Expresion newAcordeRes, NotificationChain msgs)
  {
    Expresion oldAcordeRes = acordeRes;
    acordeRes = newAcordeRes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAVE__ACORDE_RES, oldAcordeRes, newAcordeRes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAcordeRes(Expresion newAcordeRes)
  {
    if (newAcordeRes != acordeRes)
    {
      NotificationChain msgs = null;
      if (acordeRes != null)
        msgs = ((InternalEObject)acordeRes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MadonnaPackage.LLAVE__ACORDE_RES, null, msgs);
      if (newAcordeRes != null)
        msgs = ((InternalEObject)newAcordeRes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MadonnaPackage.LLAVE__ACORDE_RES, null, msgs);
      msgs = basicSetAcordeRes(newAcordeRes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAVE__ACORDE_RES, newAcordeRes, newAcordeRes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion getRep()
  {
    return rep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRep(Expresion newRep, NotificationChain msgs)
  {
    Expresion oldRep = rep;
    rep = newRep;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAVE__REP, oldRep, newRep);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRep(Expresion newRep)
  {
    if (newRep != rep)
    {
      NotificationChain msgs = null;
      if (rep != null)
        msgs = ((InternalEObject)rep).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MadonnaPackage.LLAVE__REP, null, msgs);
      if (newRep != null)
        msgs = ((InternalEObject)newRep).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MadonnaPackage.LLAVE__REP, null, msgs);
      msgs = basicSetRep(newRep, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MadonnaPackage.LLAVE__REP, newRep, newRep));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAVE__EXPR_LOG_CONDICION:
        return basicSetExprLogCondicion(null, msgs);
      case MadonnaPackage.LLAVE__ACORDE_RES:
        return basicSetAcordeRes(null, msgs);
      case MadonnaPackage.LLAVE__REP:
        return basicSetRep(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAVE__EXPR_LOG_CONDICION:
        return getExprLogCondicion();
      case MadonnaPackage.LLAVE__ACORDE_RES:
        return getAcordeRes();
      case MadonnaPackage.LLAVE__REP:
        return getRep();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAVE__EXPR_LOG_CONDICION:
        setExprLogCondicion((Expresion)newValue);
        return;
      case MadonnaPackage.LLAVE__ACORDE_RES:
        setAcordeRes((Expresion)newValue);
        return;
      case MadonnaPackage.LLAVE__REP:
        setRep((Expresion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAVE__EXPR_LOG_CONDICION:
        setExprLogCondicion((Expresion)null);
        return;
      case MadonnaPackage.LLAVE__ACORDE_RES:
        setAcordeRes((Expresion)null);
        return;
      case MadonnaPackage.LLAVE__REP:
        setRep((Expresion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MadonnaPackage.LLAVE__EXPR_LOG_CONDICION:
        return exprLogCondicion != null;
      case MadonnaPackage.LLAVE__ACORDE_RES:
        return acordeRes != null;
      case MadonnaPackage.LLAVE__REP:
        return rep != null;
    }
    return super.eIsSet(featureID);
  }

} //LlaveImpl
