/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import upb.lp.edu.madonna.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MadonnaFactoryImpl extends EFactoryImpl implements MadonnaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MadonnaFactory init()
  {
    try
    {
      MadonnaFactory theMadonnaFactory = (MadonnaFactory)EPackage.Registry.INSTANCE.getEFactory(MadonnaPackage.eNS_URI);
      if (theMadonnaFactory != null)
      {
        return theMadonnaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MadonnaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MadonnaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MadonnaPackage.PROGRAMA: return createPrograma();
      case MadonnaPackage.PRINT: return createPrint();
      case MadonnaPackage.INSTRUCCIONES: return createInstrucciones();
      case MadonnaPackage.LLAVE: return createLlave();
      case MadonnaPackage.LLAMADO_FUNC: return createLlamadoFunc();
      case MadonnaPackage.DECLARACION: return createDeclaracion();
      case MadonnaPackage.FUNCION: return createFuncion();
      case MadonnaPackage.ASIGNACION_NOTA: return createAsignacionNota();
      case MadonnaPackage.ASIGNACION_MELODIA: return createAsignacionMelodia();
      case MadonnaPackage.ASIGNACION_SUB_NOTA: return createAsignacionSubNota();
      case MadonnaPackage.ASIGNACION_RITMO: return createAsignacionRitmo();
      case MadonnaPackage.PARAM: return createParam();
      case MadonnaPackage.CONSTANTE: return createConstante();
      case MadonnaPackage.VALOR: return createValor();
      case MadonnaPackage.EXPRESION: return createExpresion();
      case MadonnaPackage.EXPR_CONCATENACION: return createExprConcatenacion();
      case MadonnaPackage.EXPR_ARITMETICA: return createExprAritmetica();
      case MadonnaPackage.EXPR_LOGICA: return createExprLogica();
      case MadonnaPackage.EXPR_LOGICA_OPERADORES: return createExprLogicaOperadores();
      case MadonnaPackage.EXPR_COMPARACION: return createExprComparacion();
      case MadonnaPackage.PRIMITIVO: return createPrimitivo();
      case MadonnaPackage.NOTA: return createNota();
      case MadonnaPackage.MELODIA: return createMelodia();
      case MadonnaPackage.SUB_NOTA: return createSubNota();
      case MadonnaPackage.RITMO: return createRitmo();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Programa createPrograma()
  {
    ProgramaImpl programa = new ProgramaImpl();
    return programa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Print createPrint()
  {
    PrintImpl print = new PrintImpl();
    return print;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Instrucciones createInstrucciones()
  {
    InstruccionesImpl instrucciones = new InstruccionesImpl();
    return instrucciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Llave createLlave()
  {
    LlaveImpl llave = new LlaveImpl();
    return llave;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LlamadoFunc createLlamadoFunc()
  {
    LlamadoFuncImpl llamadoFunc = new LlamadoFuncImpl();
    return llamadoFunc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaracion createDeclaracion()
  {
    DeclaracionImpl declaracion = new DeclaracionImpl();
    return declaracion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Funcion createFuncion()
  {
    FuncionImpl funcion = new FuncionImpl();
    return funcion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AsignacionNota createAsignacionNota()
  {
    AsignacionNotaImpl asignacionNota = new AsignacionNotaImpl();
    return asignacionNota;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AsignacionMelodia createAsignacionMelodia()
  {
    AsignacionMelodiaImpl asignacionMelodia = new AsignacionMelodiaImpl();
    return asignacionMelodia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AsignacionSubNota createAsignacionSubNota()
  {
    AsignacionSubNotaImpl asignacionSubNota = new AsignacionSubNotaImpl();
    return asignacionSubNota;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AsignacionRitmo createAsignacionRitmo()
  {
    AsignacionRitmoImpl asignacionRitmo = new AsignacionRitmoImpl();
    return asignacionRitmo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Param createParam()
  {
    ParamImpl param = new ParamImpl();
    return param;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Constante createConstante()
  {
    ConstanteImpl constante = new ConstanteImpl();
    return constante;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Valor createValor()
  {
    ValorImpl valor = new ValorImpl();
    return valor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expresion createExpresion()
  {
    ExpresionImpl expresion = new ExpresionImpl();
    return expresion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprConcatenacion createExprConcatenacion()
  {
    ExprConcatenacionImpl exprConcatenacion = new ExprConcatenacionImpl();
    return exprConcatenacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprAritmetica createExprAritmetica()
  {
    ExprAritmeticaImpl exprAritmetica = new ExprAritmeticaImpl();
    return exprAritmetica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprLogica createExprLogica()
  {
    ExprLogicaImpl exprLogica = new ExprLogicaImpl();
    return exprLogica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprLogicaOperadores createExprLogicaOperadores()
  {
    ExprLogicaOperadoresImpl exprLogicaOperadores = new ExprLogicaOperadoresImpl();
    return exprLogicaOperadores;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprComparacion createExprComparacion()
  {
    ExprComparacionImpl exprComparacion = new ExprComparacionImpl();
    return exprComparacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Primitivo createPrimitivo()
  {
    PrimitivoImpl primitivo = new PrimitivoImpl();
    return primitivo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nota createNota()
  {
    NotaImpl nota = new NotaImpl();
    return nota;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Melodia createMelodia()
  {
    MelodiaImpl melodia = new MelodiaImpl();
    return melodia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SubNota createSubNota()
  {
    SubNotaImpl subNota = new SubNotaImpl();
    return subNota;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ritmo createRitmo()
  {
    RitmoImpl ritmo = new RitmoImpl();
    return ritmo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MadonnaPackage getMadonnaPackage()
  {
    return (MadonnaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MadonnaPackage getPackage()
  {
    return MadonnaPackage.eINSTANCE;
  }

} //MadonnaFactoryImpl
