/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.impl;

import org.eclipse.emf.ecore.EClass;

import upb.lp.edu.madonna.MadonnaPackage;
import upb.lp.edu.madonna.Valor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Valor</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ValorImpl extends InstruccionesImpl implements Valor
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MadonnaPackage.Literals.VALOR;
  }

} //ValorImpl
