/**
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.madonna.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import upb.lp.edu.madonna.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see upb.lp.edu.madonna.MadonnaPackage
 * @generated
 */
public class MadonnaAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MadonnaPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MadonnaAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = MadonnaPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MadonnaSwitch<Adapter> modelSwitch =
    new MadonnaSwitch<Adapter>()
    {
      @Override
      public Adapter casePrograma(Programa object)
      {
        return createProgramaAdapter();
      }
      @Override
      public Adapter casePrint(Print object)
      {
        return createPrintAdapter();
      }
      @Override
      public Adapter caseInstrucciones(Instrucciones object)
      {
        return createInstruccionesAdapter();
      }
      @Override
      public Adapter caseLlave(Llave object)
      {
        return createLlaveAdapter();
      }
      @Override
      public Adapter caseLlamadoFunc(LlamadoFunc object)
      {
        return createLlamadoFuncAdapter();
      }
      @Override
      public Adapter caseDeclaracion(Declaracion object)
      {
        return createDeclaracionAdapter();
      }
      @Override
      public Adapter caseFuncion(Funcion object)
      {
        return createFuncionAdapter();
      }
      @Override
      public Adapter caseAsignacionNota(AsignacionNota object)
      {
        return createAsignacionNotaAdapter();
      }
      @Override
      public Adapter caseAsignacionMelodia(AsignacionMelodia object)
      {
        return createAsignacionMelodiaAdapter();
      }
      @Override
      public Adapter caseAsignacionSubNota(AsignacionSubNota object)
      {
        return createAsignacionSubNotaAdapter();
      }
      @Override
      public Adapter caseAsignacionRitmo(AsignacionRitmo object)
      {
        return createAsignacionRitmoAdapter();
      }
      @Override
      public Adapter caseParam(Param object)
      {
        return createParamAdapter();
      }
      @Override
      public Adapter caseConstante(Constante object)
      {
        return createConstanteAdapter();
      }
      @Override
      public Adapter caseValor(Valor object)
      {
        return createValorAdapter();
      }
      @Override
      public Adapter caseExpresion(Expresion object)
      {
        return createExpresionAdapter();
      }
      @Override
      public Adapter caseExprConcatenacion(ExprConcatenacion object)
      {
        return createExprConcatenacionAdapter();
      }
      @Override
      public Adapter caseExprAritmetica(ExprAritmetica object)
      {
        return createExprAritmeticaAdapter();
      }
      @Override
      public Adapter caseExprLogica(ExprLogica object)
      {
        return createExprLogicaAdapter();
      }
      @Override
      public Adapter caseExprLogicaOperadores(ExprLogicaOperadores object)
      {
        return createExprLogicaOperadoresAdapter();
      }
      @Override
      public Adapter caseExprComparacion(ExprComparacion object)
      {
        return createExprComparacionAdapter();
      }
      @Override
      public Adapter casePrimitivo(Primitivo object)
      {
        return createPrimitivoAdapter();
      }
      @Override
      public Adapter caseNota(Nota object)
      {
        return createNotaAdapter();
      }
      @Override
      public Adapter caseMelodia(Melodia object)
      {
        return createMelodiaAdapter();
      }
      @Override
      public Adapter caseSubNota(SubNota object)
      {
        return createSubNotaAdapter();
      }
      @Override
      public Adapter caseRitmo(Ritmo object)
      {
        return createRitmoAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Programa
   * @generated
   */
  public Adapter createProgramaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Print
   * @generated
   */
  public Adapter createPrintAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Instrucciones <em>Instrucciones</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Instrucciones
   * @generated
   */
  public Adapter createInstruccionesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Llave <em>Llave</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Llave
   * @generated
   */
  public Adapter createLlaveAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.LlamadoFunc <em>Llamado Func</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.LlamadoFunc
   * @generated
   */
  public Adapter createLlamadoFuncAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Declaracion <em>Declaracion</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Declaracion
   * @generated
   */
  public Adapter createDeclaracionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Funcion <em>Funcion</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Funcion
   * @generated
   */
  public Adapter createFuncionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.AsignacionNota <em>Asignacion Nota</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.AsignacionNota
   * @generated
   */
  public Adapter createAsignacionNotaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.AsignacionMelodia <em>Asignacion Melodia</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.AsignacionMelodia
   * @generated
   */
  public Adapter createAsignacionMelodiaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.AsignacionSubNota <em>Asignacion Sub Nota</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.AsignacionSubNota
   * @generated
   */
  public Adapter createAsignacionSubNotaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.AsignacionRitmo <em>Asignacion Ritmo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.AsignacionRitmo
   * @generated
   */
  public Adapter createAsignacionRitmoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Param
   * @generated
   */
  public Adapter createParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Constante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Constante
   * @generated
   */
  public Adapter createConstanteAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Valor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Valor
   * @generated
   */
  public Adapter createValorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Expresion <em>Expresion</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Expresion
   * @generated
   */
  public Adapter createExpresionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.ExprConcatenacion <em>Expr Concatenacion</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.ExprConcatenacion
   * @generated
   */
  public Adapter createExprConcatenacionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.ExprAritmetica <em>Expr Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.ExprAritmetica
   * @generated
   */
  public Adapter createExprAritmeticaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.ExprLogica <em>Expr Logica</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.ExprLogica
   * @generated
   */
  public Adapter createExprLogicaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.ExprLogicaOperadores <em>Expr Logica Operadores</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.ExprLogicaOperadores
   * @generated
   */
  public Adapter createExprLogicaOperadoresAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.ExprComparacion <em>Expr Comparacion</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.ExprComparacion
   * @generated
   */
  public Adapter createExprComparacionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Primitivo <em>Primitivo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Primitivo
   * @generated
   */
  public Adapter createPrimitivoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Nota <em>Nota</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Nota
   * @generated
   */
  public Adapter createNotaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Melodia <em>Melodia</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Melodia
   * @generated
   */
  public Adapter createMelodiaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.SubNota <em>Sub Nota</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.SubNota
   * @generated
   */
  public Adapter createSubNotaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link upb.lp.edu.madonna.Ritmo <em>Ritmo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see upb.lp.edu.madonna.Ritmo
   * @generated
   */
  public Adapter createRitmoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //MadonnaAdapterFactory
