/*
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMadonnaScopeProvider extends DelegatingScopeProvider {
}
