/*
 * generated by Xtext 2.31.0
 */
package upb.lp.edu.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MadonnaGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Programa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComposicionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cProgAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cProgInstruccionesParserRuleCall_2_0 = (RuleCall)cProgAssignment_2.eContents().get(0);
		
		//Programa:
		//    'Composicion' name=ID
		//    (prog+=Instrucciones)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Composicion' name=ID
		//(prog+=Instrucciones)*
		public Group getGroup() { return cGroup; }
		
		//'Composicion'
		public Keyword getComposicionKeyword_0() { return cComposicionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//(prog+=Instrucciones)*
		public Assignment getProgAssignment_2() { return cProgAssignment_2; }
		
		//Instrucciones
		public RuleCall getProgInstruccionesParserRuleCall_2_0() { return cProgInstruccionesParserRuleCall_2_0; }
	}
	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPrintTipoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cPrintTipoAlternatives_0_0 = (Alternatives)cPrintTipoAssignment_0.eContents().get(0);
		private final Keyword cPrintTipoMelodiaKeyword_0_0_0 = (Keyword)cPrintTipoAlternatives_0_0.eContents().get(0);
		private final Keyword cPrintTipoMelodiaLinealKeyword_0_0_1 = (Keyword)cPrintTipoAlternatives_0_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValValorParserRuleCall_2_0 = (RuleCall)cValAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Print:
		//    printTipo=('Melodia' | 'MelodiaLineal') '(' (val=Valor) ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//printTipo=('Melodia' | 'MelodiaLineal') '(' (val=Valor) ')'
		public Group getGroup() { return cGroup; }
		
		//printTipo=('Melodia' | 'MelodiaLineal')
		public Assignment getPrintTipoAssignment_0() { return cPrintTipoAssignment_0; }
		
		//('Melodia' | 'MelodiaLineal')
		public Alternatives getPrintTipoAlternatives_0_0() { return cPrintTipoAlternatives_0_0; }
		
		//'Melodia'
		public Keyword getPrintTipoMelodiaKeyword_0_0_0() { return cPrintTipoMelodiaKeyword_0_0_0; }
		
		//'MelodiaLineal'
		public Keyword getPrintTipoMelodiaLinealKeyword_0_0_1() { return cPrintTipoMelodiaLinealKeyword_0_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//(val=Valor)
		public Assignment getValAssignment_2() { return cValAssignment_2; }
		
		//Valor
		public RuleCall getValValorParserRuleCall_2_0() { return cValValorParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class InstruccionesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Instrucciones");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDeclaracionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cValorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Instrucciones:
		//    (Declaracion | Valor)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(Declaracion | Valor)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Declaracion
		public RuleCall getDeclaracionParserRuleCall_0() { return cDeclaracionParserRuleCall_0; }
		
		//Valor
		public RuleCall getValorParserRuleCall_1() { return cValorParserRuleCall_1; }
	}
	public class LlaveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Llave");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cLlaveKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cExprLogCondicionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cExprLogCondicionExpresionParserRuleCall_0_2_0 = (RuleCall)cExprLogCondicionAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cAcordeResAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cAcordeResExpresionParserRuleCall_0_4_0 = (RuleCall)cAcordeResAssignment_0_4.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cReproduceKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRepAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRepExpresionParserRuleCall_1_1_0 = (RuleCall)cRepAssignment_1_1.eContents().get(0);
		
		//Llave:
		//    ('Llave' '(' exprLogCondicion=(Expresion)')' acordeRes = Expresion)
		//    ('Reproduce' Rep = Expresion)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('Llave' '(' exprLogCondicion=(Expresion)')' acordeRes = Expresion)
		//('Reproduce' Rep = Expresion)
		public Group getGroup() { return cGroup; }
		
		//('Llave' '(' exprLogCondicion=(Expresion)')' acordeRes = Expresion)
		public Group getGroup_0() { return cGroup_0; }
		
		//'Llave'
		public Keyword getLlaveKeyword_0_0() { return cLlaveKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//exprLogCondicion=(Expresion)
		public Assignment getExprLogCondicionAssignment_0_2() { return cExprLogCondicionAssignment_0_2; }
		
		//(Expresion)
		public RuleCall getExprLogCondicionExpresionParserRuleCall_0_2_0() { return cExprLogCondicionExpresionParserRuleCall_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//acordeRes = Expresion
		public Assignment getAcordeResAssignment_0_4() { return cAcordeResAssignment_0_4; }
		
		//Expresion
		public RuleCall getAcordeResExpresionParserRuleCall_0_4_0() { return cAcordeResExpresionParserRuleCall_0_4_0; }
		
		//('Reproduce' Rep = Expresion)
		public Group getGroup_1() { return cGroup_1; }
		
		//'Reproduce'
		public Keyword getReproduceKeyword_1_0() { return cReproduceKeyword_1_0; }
		
		//Rep = Expresion
		public Assignment getRepAssignment_1_1() { return cRepAssignment_1_1; }
		
		//Expresion
		public RuleCall getRepExpresionParserRuleCall_1_1_0() { return cRepExpresionParserRuleCall_1_1_0; }
	}
	public class LlamadoFuncElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.LlamadoFunc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFuncionIDAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cFuncionIDDeclaracionCrossReference_0_0 = (CrossReference)cFuncionIDAssignment_0.eContents().get(0);
		private final RuleCall cFuncionIDDeclaracionIDTerminalRuleCall_0_0_1 = (RuleCall)cFuncionIDDeclaracionCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cArgsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArgsValorParserRuleCall_2_0 = (RuleCall)cArgsAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//LlamadoFunc:
		//    funcionID=[Declaracion] '(' (args+=(Valor) )? ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//funcionID=[Declaracion] '(' (args+=(Valor) )? ')'
		public Group getGroup() { return cGroup; }
		
		//funcionID=[Declaracion]
		public Assignment getFuncionIDAssignment_0() { return cFuncionIDAssignment_0; }
		
		//[Declaracion]
		public CrossReference getFuncionIDDeclaracionCrossReference_0_0() { return cFuncionIDDeclaracionCrossReference_0_0; }
		
		//ID
		public RuleCall getFuncionIDDeclaracionIDTerminalRuleCall_0_0_1() { return cFuncionIDDeclaracionIDTerminalRuleCall_0_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//(args+=(Valor) )?
		public Assignment getArgsAssignment_2() { return cArgsAssignment_2; }
		
		//(Valor)
		public RuleCall getArgsValorParserRuleCall_2_0() { return cArgsValorParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class DeclaracionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Declaracion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAsignacionNotaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAsignacionMelodiaParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAsignacionSubNotaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAsignacionRitmoParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFuncionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cParamParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cPrintParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Declaracion:
		//    (AsignacionNota | AsignacionMelodia | AsignacionSubNota | AsignacionRitmo |  Funcion | Param | Print)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(AsignacionNota | AsignacionMelodia | AsignacionSubNota | AsignacionRitmo |  Funcion | Param | Print)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AsignacionNota
		public RuleCall getAsignacionNotaParserRuleCall_0() { return cAsignacionNotaParserRuleCall_0; }
		
		//AsignacionMelodia
		public RuleCall getAsignacionMelodiaParserRuleCall_1() { return cAsignacionMelodiaParserRuleCall_1; }
		
		//AsignacionSubNota
		public RuleCall getAsignacionSubNotaParserRuleCall_2() { return cAsignacionSubNotaParserRuleCall_2; }
		
		//AsignacionRitmo
		public RuleCall getAsignacionRitmoParserRuleCall_3() { return cAsignacionRitmoParserRuleCall_3; }
		
		//Funcion
		public RuleCall getFuncionParserRuleCall_4() { return cFuncionParserRuleCall_4; }
		
		//Param
		public RuleCall getParamParserRuleCall_5() { return cParamParserRuleCall_5; }
		
		//Print
		public RuleCall getPrintParserRuleCall_6() { return cPrintParserRuleCall_6; }
	}
	public class FuncionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Funcion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSeccionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cUsaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cParamAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cParamParamParserRuleCall_2_2_0 = (RuleCall)cParamAssignment_2_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Assignment cDeclarAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDeclarDeclaracionParserRuleCall_3_0 = (RuleCall)cDeclarAssignment_3.eContents().get(0);
		private final Assignment cValAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValValorParserRuleCall_4_0 = (RuleCall)cValAssignment_4.eContents().get(0);
		
		//Funcion:
		//    'Seccion' name=ID ('Usa' '(' param+=Param ')' )?
		//    (declar+=(Declaracion))*
		//    (val=(Valor))
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Seccion' name=ID ('Usa' '(' param+=Param ')' )?
		//(declar+=(Declaracion))*
		//(val=(Valor))
		public Group getGroup() { return cGroup; }
		
		//'Seccion'
		public Keyword getSeccionKeyword_0() { return cSeccionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('Usa' '(' param+=Param ')' )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Usa'
		public Keyword getUsaKeyword_2_0() { return cUsaKeyword_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1() { return cLeftParenthesisKeyword_2_1; }
		
		//param+=Param
		public Assignment getParamAssignment_2_2() { return cParamAssignment_2_2; }
		
		//Param
		public RuleCall getParamParamParserRuleCall_2_2_0() { return cParamParamParserRuleCall_2_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_3() { return cRightParenthesisKeyword_2_3; }
		
		//(declar+=(Declaracion))*
		public Assignment getDeclarAssignment_3() { return cDeclarAssignment_3; }
		
		//(Declaracion)
		public RuleCall getDeclarDeclaracionParserRuleCall_3_0() { return cDeclarDeclaracionParserRuleCall_3_0; }
		
		//(val=(Valor))
		public Assignment getValAssignment_4() { return cValAssignment_4; }
		
		//(Valor)
		public RuleCall getValValorParserRuleCall_4_0() { return cValValorParserRuleCall_4_0; }
	}
	public class AsignacionNotaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.AsignacionNota");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cValNotaCrossReference_1_0 = (CrossReference)cValAssignment_1.eContents().get(0);
		private final RuleCall cValNotaIDTerminalRuleCall_1_0_1 = (RuleCall)cValNotaCrossReference_1_0.eContents().get(1);
		
		//AsignacionNota:
		//    name=ID val=[Nota]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID val=[Nota]
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//val=[Nota]
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//[Nota]
		public CrossReference getValNotaCrossReference_1_0() { return cValNotaCrossReference_1_0; }
		
		//ID
		public RuleCall getValNotaIDTerminalRuleCall_1_0_1() { return cValNotaIDTerminalRuleCall_1_0_1; }
	}
	public class AsignacionMelodiaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.AsignacionMelodia");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cValMelodiaCrossReference_1_0 = (CrossReference)cValAssignment_1.eContents().get(0);
		private final RuleCall cValMelodiaIDTerminalRuleCall_1_0_1 = (RuleCall)cValMelodiaCrossReference_1_0.eContents().get(1);
		
		//AsignacionMelodia:
		//    name=ID val=[Melodia]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID val=[Melodia]
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//val=[Melodia]
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//[Melodia]
		public CrossReference getValMelodiaCrossReference_1_0() { return cValMelodiaCrossReference_1_0; }
		
		//ID
		public RuleCall getValMelodiaIDTerminalRuleCall_1_0_1() { return cValMelodiaIDTerminalRuleCall_1_0_1; }
	}
	public class AsignacionSubNotaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.AsignacionSubNota");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cValSubNotaCrossReference_1_0 = (CrossReference)cValAssignment_1.eContents().get(0);
		private final RuleCall cValSubNotaIDTerminalRuleCall_1_0_1 = (RuleCall)cValSubNotaCrossReference_1_0.eContents().get(1);
		
		//AsignacionSubNota:
		//    name=ID val=[SubNota]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID val=[SubNota]
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//val=[SubNota]
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//[SubNota]
		public CrossReference getValSubNotaCrossReference_1_0() { return cValSubNotaCrossReference_1_0; }
		
		//ID
		public RuleCall getValSubNotaIDTerminalRuleCall_1_0_1() { return cValSubNotaIDTerminalRuleCall_1_0_1; }
	}
	public class AsignacionRitmoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.AsignacionRitmo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cValRitmoCrossReference_1_0 = (CrossReference)cValAssignment_1.eContents().get(0);
		private final RuleCall cValRitmoIDTerminalRuleCall_1_0_1 = (RuleCall)cValRitmoCrossReference_1_0.eContents().get(1);
		
		//AsignacionRitmo:
		//    name=ID val=[Ritmo]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID val=[Ritmo]
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//val=[Ritmo]
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//[Ritmo]
		public CrossReference getValRitmoCrossReference_1_0() { return cValRitmoCrossReference_1_0; }
		
		//ID
		public RuleCall getValRitmoIDTerminalRuleCall_1_0_1() { return cValRitmoIDTerminalRuleCall_1_0_1; }
	}
	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Param");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimitivoParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Param:
		//   Primitivo name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Primitivo name=ID
		public Group getGroup() { return cGroup; }
		
		//Primitivo
		public RuleCall getPrimitivoParserRuleCall_0() { return cPrimitivoParserRuleCall_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class ConstanteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Constante");
		private final Assignment cNombreAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cNombreDeclaracionCrossReference_0 = (CrossReference)cNombreAssignment.eContents().get(0);
		private final RuleCall cNombreDeclaracionIDTerminalRuleCall_0_1 = (RuleCall)cNombreDeclaracionCrossReference_0.eContents().get(1);
		
		//Constante:
		//    nombre=[Declaracion]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//nombre=[Declaracion]
		public Assignment getNombreAssignment() { return cNombreAssignment; }
		
		//[Declaracion]
		public CrossReference getNombreDeclaracionCrossReference_0() { return cNombreDeclaracionCrossReference_0; }
		
		//ID
		public RuleCall getNombreDeclaracionIDTerminalRuleCall_0_1() { return cNombreDeclaracionIDTerminalRuleCall_0_1; }
	}
	public class ValorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Valor");
		private final RuleCall cExpresionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Valor:
		//    (Expresion)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(Expresion)
		public RuleCall getExpresionParserRuleCall() { return cExpresionParserRuleCall; }
	}
	public class ExpresionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Expresion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExprConcatenacionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExprAritmeticaParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cExprLogicaParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLlamadoFuncParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cLlaveParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cConstanteParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Expresion:
		//    ExprConcatenacion | ExprAritmetica | ExprLogica | LlamadoFunc | Llave| Constante
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ExprConcatenacion | ExprAritmetica | ExprLogica | LlamadoFunc | Llave| Constante
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ExprConcatenacion
		public RuleCall getExprConcatenacionParserRuleCall_0() { return cExprConcatenacionParserRuleCall_0; }
		
		//ExprAritmetica
		public RuleCall getExprAritmeticaParserRuleCall_1() { return cExprAritmeticaParserRuleCall_1; }
		
		//ExprLogica
		public RuleCall getExprLogicaParserRuleCall_2() { return cExprLogicaParserRuleCall_2; }
		
		//LlamadoFunc
		public RuleCall getLlamadoFuncParserRuleCall_3() { return cLlamadoFuncParserRuleCall_3; }
		
		//Llave
		public RuleCall getLlaveParserRuleCall_4() { return cLlaveParserRuleCall_4; }
		
		//Constante
		public RuleCall getConstanteParserRuleCall_5() { return cConstanteParserRuleCall_5; }
	}
	public class ExprConcatenacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.ExprConcatenacion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Assignment cOperadorConAssignment_0_1_0 = (Assignment)cGroup_0_1.eContents().get(0);
		private final Keyword cOperadorConPlusSignPlusSignKeyword_0_1_0_0 = (Keyword)cOperadorConAssignment_0_1_0.eContents().get(0);
		private final Assignment cExprConAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cExprConExpresionParserRuleCall_0_1_1_0 = (RuleCall)cExprConAssignment_0_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final RuleCall cMelodiaParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ExprConcatenacion:
		//    '('(operadorCon = ('++') (exprCon+=(Expresion))+) ')' |  Melodia
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'('(operadorCon = ('++') (exprCon+=(Expresion))+) ')' |  Melodia
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'('(operadorCon = ('++') (exprCon+=(Expresion))+) ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//(operadorCon = ('++') (exprCon+=(Expresion))+)
		public Group getGroup_0_1() { return cGroup_0_1; }
		
		//operadorCon = ('++')
		public Assignment getOperadorConAssignment_0_1_0() { return cOperadorConAssignment_0_1_0; }
		
		//('++')
		public Keyword getOperadorConPlusSignPlusSignKeyword_0_1_0_0() { return cOperadorConPlusSignPlusSignKeyword_0_1_0_0; }
		
		//(exprCon+=(Expresion))+
		public Assignment getExprConAssignment_0_1_1() { return cExprConAssignment_0_1_1; }
		
		//(Expresion)
		public RuleCall getExprConExpresionParserRuleCall_0_1_1_0() { return cExprConExpresionParserRuleCall_0_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//Melodia
		public RuleCall getMelodiaParserRuleCall_1() { return cMelodiaParserRuleCall_1; }
	}
	public class ExprAritmeticaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.ExprAritmetica");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Assignment cOperadorArAssignment_0_1_0 = (Assignment)cGroup_0_1.eContents().get(0);
		private final Alternatives cOperadorArAlternatives_0_1_0_0 = (Alternatives)cOperadorArAssignment_0_1_0.eContents().get(0);
		private final Keyword cOperadorArPlusSignKeyword_0_1_0_0_0 = (Keyword)cOperadorArAlternatives_0_1_0_0.eContents().get(0);
		private final Keyword cOperadorArHyphenMinusKeyword_0_1_0_0_1 = (Keyword)cOperadorArAlternatives_0_1_0_0.eContents().get(1);
		private final Keyword cOperadorArSolidusKeyword_0_1_0_0_2 = (Keyword)cOperadorArAlternatives_0_1_0_0.eContents().get(2);
		private final Keyword cOperadorArAsteriskKeyword_0_1_0_0_3 = (Keyword)cOperadorArAlternatives_0_1_0_0.eContents().get(3);
		private final Keyword cOperadorArPercentSignKeyword_0_1_0_0_4 = (Keyword)cOperadorArAlternatives_0_1_0_0.eContents().get(4);
		private final Assignment cExprArAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cExprArExpresionParserRuleCall_0_1_1_0 = (RuleCall)cExprArAssignment_0_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Alternatives cAlternatives_1 = (Alternatives)cAlternatives.eContents().get(1);
		private final RuleCall cNotaParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cSubNotaParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//ExprAritmetica:
		//    '('(operadorAr = ('+' | '-' | '/' | '*' | '%')  (exprAr+=(Expresion))+) ')' |  (Nota | SubNota)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'('(operadorAr = ('+' | '-' | '/' | '*' | '%')  (exprAr+=(Expresion))+) ')' |  (Nota | SubNota)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'('(operadorAr = ('+' | '-' | '/' | '*' | '%')  (exprAr+=(Expresion))+) ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }
		
		//(operadorAr = ('+' | '-' | '/' | '*' | '%')  (exprAr+=(Expresion))+)
		public Group getGroup_0_1() { return cGroup_0_1; }
		
		//operadorAr = ('+' | '-' | '/' | '*' | '%')
		public Assignment getOperadorArAssignment_0_1_0() { return cOperadorArAssignment_0_1_0; }
		
		//('+' | '-' | '/' | '*' | '%')
		public Alternatives getOperadorArAlternatives_0_1_0_0() { return cOperadorArAlternatives_0_1_0_0; }
		
		//'+'
		public Keyword getOperadorArPlusSignKeyword_0_1_0_0_0() { return cOperadorArPlusSignKeyword_0_1_0_0_0; }
		
		//'-'
		public Keyword getOperadorArHyphenMinusKeyword_0_1_0_0_1() { return cOperadorArHyphenMinusKeyword_0_1_0_0_1; }
		
		//'/'
		public Keyword getOperadorArSolidusKeyword_0_1_0_0_2() { return cOperadorArSolidusKeyword_0_1_0_0_2; }
		
		//'*'
		public Keyword getOperadorArAsteriskKeyword_0_1_0_0_3() { return cOperadorArAsteriskKeyword_0_1_0_0_3; }
		
		//'%'
		public Keyword getOperadorArPercentSignKeyword_0_1_0_0_4() { return cOperadorArPercentSignKeyword_0_1_0_0_4; }
		
		//(exprAr+=(Expresion))+
		public Assignment getExprArAssignment_0_1_1() { return cExprArAssignment_0_1_1; }
		
		//(Expresion)
		public RuleCall getExprArExpresionParserRuleCall_0_1_1_0() { return cExprArExpresionParserRuleCall_0_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_2() { return cRightParenthesisKeyword_0_2; }
		
		//(Nota | SubNota)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//Nota
		public RuleCall getNotaParserRuleCall_1_0() { return cNotaParserRuleCall_1_0; }
		
		//SubNota
		public RuleCall getSubNotaParserRuleCall_1_1() { return cSubNotaParserRuleCall_1_1; }
	}
	public class ExprLogicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.ExprLogica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNegadoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNegadoExclamationMarkKeyword_0_0 = (Keyword)cNegadoAssignment_0.eContents().get(0);
		private final Assignment cExprLogAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cExprLogAlternatives_1_0 = (Alternatives)cExprLogAssignment_1.eContents().get(0);
		private final RuleCall cExprLogExprLogicaOperadoresParserRuleCall_1_0_0 = (RuleCall)cExprLogAlternatives_1_0.eContents().get(0);
		private final RuleCall cExprLogRitmoParserRuleCall_1_0_1 = (RuleCall)cExprLogAlternatives_1_0.eContents().get(1);
		private final RuleCall cExprLogExprComparacionParserRuleCall_1_0_2 = (RuleCall)cExprLogAlternatives_1_0.eContents().get(2);
		
		//ExprLogica:
		//   (Negado ?= '!')? exprLog=(ExprLogicaOperadores | Ritmo | ExprComparacion )
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(Negado ?= '!')? exprLog=(ExprLogicaOperadores | Ritmo | ExprComparacion )
		public Group getGroup() { return cGroup; }
		
		//(Negado ?= '!')?
		public Assignment getNegadoAssignment_0() { return cNegadoAssignment_0; }
		
		//'!'
		public Keyword getNegadoExclamationMarkKeyword_0_0() { return cNegadoExclamationMarkKeyword_0_0; }
		
		//exprLog=(ExprLogicaOperadores | Ritmo | ExprComparacion )
		public Assignment getExprLogAssignment_1() { return cExprLogAssignment_1; }
		
		//(ExprLogicaOperadores | Ritmo | ExprComparacion )
		public Alternatives getExprLogAlternatives_1_0() { return cExprLogAlternatives_1_0; }
		
		//ExprLogicaOperadores
		public RuleCall getExprLogExprLogicaOperadoresParserRuleCall_1_0_0() { return cExprLogExprLogicaOperadoresParserRuleCall_1_0_0; }
		
		//Ritmo
		public RuleCall getExprLogRitmoParserRuleCall_1_0_1() { return cExprLogRitmoParserRuleCall_1_0_1; }
		
		//ExprComparacion
		public RuleCall getExprLogExprComparacionParserRuleCall_1_0_2() { return cExprLogExprComparacionParserRuleCall_1_0_2; }
	}
	public class ExprLogicaOperadoresElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.ExprLogicaOperadores");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cOperadorLogAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Alternatives cOperadorLogAlternatives_1_0_0 = (Alternatives)cOperadorLogAssignment_1_0.eContents().get(0);
		private final Keyword cOperadorLogAmpersandAmpersandKeyword_1_0_0_0 = (Keyword)cOperadorLogAlternatives_1_0_0.eContents().get(0);
		private final Keyword cOperadorLogVerticalLineVerticalLineKeyword_1_0_0_1 = (Keyword)cOperadorLogAlternatives_1_0_0.eContents().get(1);
		private final Assignment cExprLogsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cExprLogsExpresionParserRuleCall_1_1_0 = (RuleCall)cExprLogsAssignment_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExprLogicaOperadores:
		//    (('('(operadorLog = ( '&&' | '||' ) (exprLogs+=(Expresion))+) ')' ))
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(('('(operadorLog = ( '&&' | '||' ) (exprLogs+=(Expresion))+) ')' ))
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//(operadorLog = ( '&&' | '||' ) (exprLogs+=(Expresion))+)
		public Group getGroup_1() { return cGroup_1; }
		
		//operadorLog = ( '&&' | '||' )
		public Assignment getOperadorLogAssignment_1_0() { return cOperadorLogAssignment_1_0; }
		
		//( '&&' | '||' )
		public Alternatives getOperadorLogAlternatives_1_0_0() { return cOperadorLogAlternatives_1_0_0; }
		
		//'&&'
		public Keyword getOperadorLogAmpersandAmpersandKeyword_1_0_0_0() { return cOperadorLogAmpersandAmpersandKeyword_1_0_0_0; }
		
		//'||'
		public Keyword getOperadorLogVerticalLineVerticalLineKeyword_1_0_0_1() { return cOperadorLogVerticalLineVerticalLineKeyword_1_0_0_1; }
		
		//(exprLogs+=(Expresion))+
		public Assignment getExprLogsAssignment_1_1() { return cExprLogsAssignment_1_1; }
		
		//(Expresion)
		public RuleCall getExprLogsExpresionParserRuleCall_1_1_0() { return cExprLogsExpresionParserRuleCall_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ExprComparacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.ExprComparacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cOperadorCompAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Alternatives cOperadorCompAlternatives_1_0_0 = (Alternatives)cOperadorCompAssignment_1_0.eContents().get(0);
		private final Keyword cOperadorCompLessThanSignKeyword_1_0_0_0 = (Keyword)cOperadorCompAlternatives_1_0_0.eContents().get(0);
		private final Keyword cOperadorCompGreaterThanSignKeyword_1_0_0_1 = (Keyword)cOperadorCompAlternatives_1_0_0.eContents().get(1);
		private final Keyword cOperadorCompLessThanSignEqualsSignKeyword_1_0_0_2 = (Keyword)cOperadorCompAlternatives_1_0_0.eContents().get(2);
		private final Keyword cOperadorCompGreaterThanSignEqualsSignKeyword_1_0_0_3 = (Keyword)cOperadorCompAlternatives_1_0_0.eContents().get(3);
		private final Keyword cOperadorCompEqualsSignEqualsSignKeyword_1_0_0_4 = (Keyword)cOperadorCompAlternatives_1_0_0.eContents().get(4);
		private final Keyword cOperadorCompTildeEqualsSignKeyword_1_0_0_5 = (Keyword)cOperadorCompAlternatives_1_0_0.eContents().get(5);
		private final Assignment cExprComIzqAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cExprComIzqExpresionParserRuleCall_1_1_0 = (RuleCall)cExprComIzqAssignment_1_1.eContents().get(0);
		private final Assignment cExprComDerAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExprComDerExpresionParserRuleCall_1_2_0 = (RuleCall)cExprComDerAssignment_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExprComparacion:
		//    '('(operadorComp = ('<' | '>' | '<=' | '>=' | '==' | '~=') exprComIzq=(Expresion) exprComDer=(Expresion)) ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'('(operadorComp = ('<' | '>' | '<=' | '>=' | '==' | '~=') exprComIzq=(Expresion) exprComDer=(Expresion)) ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//(operadorComp = ('<' | '>' | '<=' | '>=' | '==' | '~=') exprComIzq=(Expresion) exprComDer=(Expresion))
		public Group getGroup_1() { return cGroup_1; }
		
		//operadorComp = ('<' | '>' | '<=' | '>=' | '==' | '~=')
		public Assignment getOperadorCompAssignment_1_0() { return cOperadorCompAssignment_1_0; }
		
		//('<' | '>' | '<=' | '>=' | '==' | '~=')
		public Alternatives getOperadorCompAlternatives_1_0_0() { return cOperadorCompAlternatives_1_0_0; }
		
		//'<'
		public Keyword getOperadorCompLessThanSignKeyword_1_0_0_0() { return cOperadorCompLessThanSignKeyword_1_0_0_0; }
		
		//'>'
		public Keyword getOperadorCompGreaterThanSignKeyword_1_0_0_1() { return cOperadorCompGreaterThanSignKeyword_1_0_0_1; }
		
		//'<='
		public Keyword getOperadorCompLessThanSignEqualsSignKeyword_1_0_0_2() { return cOperadorCompLessThanSignEqualsSignKeyword_1_0_0_2; }
		
		//'>='
		public Keyword getOperadorCompGreaterThanSignEqualsSignKeyword_1_0_0_3() { return cOperadorCompGreaterThanSignEqualsSignKeyword_1_0_0_3; }
		
		//'=='
		public Keyword getOperadorCompEqualsSignEqualsSignKeyword_1_0_0_4() { return cOperadorCompEqualsSignEqualsSignKeyword_1_0_0_4; }
		
		//'~='
		public Keyword getOperadorCompTildeEqualsSignKeyword_1_0_0_5() { return cOperadorCompTildeEqualsSignKeyword_1_0_0_5; }
		
		//exprComIzq=(Expresion)
		public Assignment getExprComIzqAssignment_1_1() { return cExprComIzqAssignment_1_1; }
		
		//(Expresion)
		public RuleCall getExprComIzqExpresionParserRuleCall_1_1_0() { return cExprComIzqExpresionParserRuleCall_1_1_0; }
		
		//exprComDer=(Expresion)
		public Assignment getExprComDerAssignment_1_2() { return cExprComDerAssignment_1_2; }
		
		//(Expresion)
		public RuleCall getExprComDerExpresionParserRuleCall_1_2_0() { return cExprComDerExpresionParserRuleCall_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class PrimitivoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Primitivo");
		private final Assignment cTipoAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cTipoAlternatives_0 = (Alternatives)cTipoAssignment.eContents().get(0);
		private final Keyword cTipoMelodiaKeyword_0_0 = (Keyword)cTipoAlternatives_0.eContents().get(0);
		private final Keyword cTipoNotaKeyword_0_1 = (Keyword)cTipoAlternatives_0.eContents().get(1);
		private final Keyword cTipoSubNotaKeyword_0_2 = (Keyword)cTipoAlternatives_0.eContents().get(2);
		private final Keyword cTipoRitmoKeyword_0_3 = (Keyword)cTipoAlternatives_0.eContents().get(3);
		
		//Primitivo:
		//    tipo = ('Melodia' |  'Nota' | 'SubNota' | 'Ritmo')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//tipo = ('Melodia' |  'Nota' | 'SubNota' | 'Ritmo')
		public Assignment getTipoAssignment() { return cTipoAssignment; }
		
		//('Melodia' |  'Nota' | 'SubNota' | 'Ritmo')
		public Alternatives getTipoAlternatives_0() { return cTipoAlternatives_0; }
		
		//'Melodia'
		public Keyword getTipoMelodiaKeyword_0_0() { return cTipoMelodiaKeyword_0_0; }
		
		//'Nota'
		public Keyword getTipoNotaKeyword_0_1() { return cTipoNotaKeyword_0_1; }
		
		//'SubNota'
		public Keyword getTipoSubNotaKeyword_0_2() { return cTipoSubNotaKeyword_0_2; }
		
		//'Ritmo'
		public Keyword getTipoRitmoKeyword_0_3() { return cTipoRitmoKeyword_0_3; }
	}
	public class NotaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Nota");
		private final Assignment cXAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cXINTTerminalRuleCall_0 = (RuleCall)cXAssignment.eContents().get(0);
		
		//Nota:
		//    x = INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//x = INT
		public Assignment getXAssignment() { return cXAssignment; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_0() { return cXINTTerminalRuleCall_0; }
	}
	public class MelodiaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Melodia");
		private final Assignment cXAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cXSTRINGTerminalRuleCall_0 = (RuleCall)cXAssignment.eContents().get(0);
		
		//Melodia:
		//    x = STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//x = STRING
		public Assignment getXAssignment() { return cXAssignment; }
		
		//STRING
		public RuleCall getXSTRINGTerminalRuleCall_0() { return cXSTRINGTerminalRuleCall_0; }
	}
	public class SubNotaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.SubNota");
		private final Assignment cXAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cXDoubleParserRuleCall_0 = (RuleCall)cXAssignment.eContents().get(0);
		
		//SubNota:
		//    x = Double
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//x = Double
		public Assignment getXAssignment() { return cXAssignment; }
		
		//Double
		public RuleCall getXDoubleParserRuleCall_0() { return cXDoubleParserRuleCall_0; }
	}
	public class DoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Double");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Double returns ecore::EDouble:
		//    INT '.' INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class RitmoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "upb.lp.edu.Madonna.Ritmo");
		private final Assignment cXAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cXAlternatives_0 = (Alternatives)cXAssignment.eContents().get(0);
		private final Keyword cXCuartoKeyword_0_0 = (Keyword)cXAlternatives_0.eContents().get(0);
		private final Keyword cXOctavoKeyword_0_1 = (Keyword)cXAlternatives_0.eContents().get(1);
		
		//Ritmo:
		//    x = ('Cuarto' | 'Octavo')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//x = ('Cuarto' | 'Octavo')
		public Assignment getXAssignment() { return cXAssignment; }
		
		//('Cuarto' | 'Octavo')
		public Alternatives getXAlternatives_0() { return cXAlternatives_0; }
		
		//'Cuarto'
		public Keyword getXCuartoKeyword_0_0() { return cXCuartoKeyword_0_0; }
		
		//'Octavo'
		public Keyword getXOctavoKeyword_0_1() { return cXOctavoKeyword_0_1; }
	}
	
	
	private final ProgramaElements pPrograma;
	private final PrintElements pPrint;
	private final InstruccionesElements pInstrucciones;
	private final LlaveElements pLlave;
	private final LlamadoFuncElements pLlamadoFunc;
	private final DeclaracionElements pDeclaracion;
	private final FuncionElements pFuncion;
	private final AsignacionNotaElements pAsignacionNota;
	private final AsignacionMelodiaElements pAsignacionMelodia;
	private final AsignacionSubNotaElements pAsignacionSubNota;
	private final AsignacionRitmoElements pAsignacionRitmo;
	private final ParamElements pParam;
	private final ConstanteElements pConstante;
	private final ValorElements pValor;
	private final ExpresionElements pExpresion;
	private final ExprConcatenacionElements pExprConcatenacion;
	private final ExprAritmeticaElements pExprAritmetica;
	private final ExprLogicaElements pExprLogica;
	private final ExprLogicaOperadoresElements pExprLogicaOperadores;
	private final ExprComparacionElements pExprComparacion;
	private final PrimitivoElements pPrimitivo;
	private final NotaElements pNota;
	private final MelodiaElements pMelodia;
	private final SubNotaElements pSubNota;
	private final DoubleElements pDouble;
	private final RitmoElements pRitmo;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MadonnaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPrograma = new ProgramaElements();
		this.pPrint = new PrintElements();
		this.pInstrucciones = new InstruccionesElements();
		this.pLlave = new LlaveElements();
		this.pLlamadoFunc = new LlamadoFuncElements();
		this.pDeclaracion = new DeclaracionElements();
		this.pFuncion = new FuncionElements();
		this.pAsignacionNota = new AsignacionNotaElements();
		this.pAsignacionMelodia = new AsignacionMelodiaElements();
		this.pAsignacionSubNota = new AsignacionSubNotaElements();
		this.pAsignacionRitmo = new AsignacionRitmoElements();
		this.pParam = new ParamElements();
		this.pConstante = new ConstanteElements();
		this.pValor = new ValorElements();
		this.pExpresion = new ExpresionElements();
		this.pExprConcatenacion = new ExprConcatenacionElements();
		this.pExprAritmetica = new ExprAritmeticaElements();
		this.pExprLogica = new ExprLogicaElements();
		this.pExprLogicaOperadores = new ExprLogicaOperadoresElements();
		this.pExprComparacion = new ExprComparacionElements();
		this.pPrimitivo = new PrimitivoElements();
		this.pNota = new NotaElements();
		this.pMelodia = new MelodiaElements();
		this.pSubNota = new SubNotaElements();
		this.pDouble = new DoubleElements();
		this.pRitmo = new RitmoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("upb.lp.edu.Madonna".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Programa:
	//    'Composicion' name=ID
	//    (prog+=Instrucciones)*
	//;
	public ProgramaElements getProgramaAccess() {
		return pPrograma;
	}
	
	public ParserRule getProgramaRule() {
		return getProgramaAccess().getRule();
	}
	
	//Print:
	//    printTipo=('Melodia' | 'MelodiaLineal') '(' (val=Valor) ')'
	//;
	public PrintElements getPrintAccess() {
		return pPrint;
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}
	
	//Instrucciones:
	//    (Declaracion | Valor)
	//;
	public InstruccionesElements getInstruccionesAccess() {
		return pInstrucciones;
	}
	
	public ParserRule getInstruccionesRule() {
		return getInstruccionesAccess().getRule();
	}
	
	//Llave:
	//    ('Llave' '(' exprLogCondicion=(Expresion)')' acordeRes = Expresion)
	//    ('Reproduce' Rep = Expresion)
	//;
	public LlaveElements getLlaveAccess() {
		return pLlave;
	}
	
	public ParserRule getLlaveRule() {
		return getLlaveAccess().getRule();
	}
	
	//LlamadoFunc:
	//    funcionID=[Declaracion] '(' (args+=(Valor) )? ')'
	//;
	public LlamadoFuncElements getLlamadoFuncAccess() {
		return pLlamadoFunc;
	}
	
	public ParserRule getLlamadoFuncRule() {
		return getLlamadoFuncAccess().getRule();
	}
	
	//Declaracion:
	//    (AsignacionNota | AsignacionMelodia | AsignacionSubNota | AsignacionRitmo |  Funcion | Param | Print)
	//;
	public DeclaracionElements getDeclaracionAccess() {
		return pDeclaracion;
	}
	
	public ParserRule getDeclaracionRule() {
		return getDeclaracionAccess().getRule();
	}
	
	//Funcion:
	//    'Seccion' name=ID ('Usa' '(' param+=Param ')' )?
	//    (declar+=(Declaracion))*
	//    (val=(Valor))
	//;
	public FuncionElements getFuncionAccess() {
		return pFuncion;
	}
	
	public ParserRule getFuncionRule() {
		return getFuncionAccess().getRule();
	}
	
	//AsignacionNota:
	//    name=ID val=[Nota]
	//;
	public AsignacionNotaElements getAsignacionNotaAccess() {
		return pAsignacionNota;
	}
	
	public ParserRule getAsignacionNotaRule() {
		return getAsignacionNotaAccess().getRule();
	}
	
	//AsignacionMelodia:
	//    name=ID val=[Melodia]
	//;
	public AsignacionMelodiaElements getAsignacionMelodiaAccess() {
		return pAsignacionMelodia;
	}
	
	public ParserRule getAsignacionMelodiaRule() {
		return getAsignacionMelodiaAccess().getRule();
	}
	
	//AsignacionSubNota:
	//    name=ID val=[SubNota]
	//;
	public AsignacionSubNotaElements getAsignacionSubNotaAccess() {
		return pAsignacionSubNota;
	}
	
	public ParserRule getAsignacionSubNotaRule() {
		return getAsignacionSubNotaAccess().getRule();
	}
	
	//AsignacionRitmo:
	//    name=ID val=[Ritmo]
	//;
	public AsignacionRitmoElements getAsignacionRitmoAccess() {
		return pAsignacionRitmo;
	}
	
	public ParserRule getAsignacionRitmoRule() {
		return getAsignacionRitmoAccess().getRule();
	}
	
	//Param:
	//   Primitivo name=ID
	//;
	public ParamElements getParamAccess() {
		return pParam;
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}
	
	//Constante:
	//    nombre=[Declaracion]
	//;
	public ConstanteElements getConstanteAccess() {
		return pConstante;
	}
	
	public ParserRule getConstanteRule() {
		return getConstanteAccess().getRule();
	}
	
	//Valor:
	//    (Expresion)
	//;
	public ValorElements getValorAccess() {
		return pValor;
	}
	
	public ParserRule getValorRule() {
		return getValorAccess().getRule();
	}
	
	//Expresion:
	//    ExprConcatenacion | ExprAritmetica | ExprLogica | LlamadoFunc | Llave| Constante
	//;
	public ExpresionElements getExpresionAccess() {
		return pExpresion;
	}
	
	public ParserRule getExpresionRule() {
		return getExpresionAccess().getRule();
	}
	
	//ExprConcatenacion:
	//    '('(operadorCon = ('++') (exprCon+=(Expresion))+) ')' |  Melodia
	//;
	public ExprConcatenacionElements getExprConcatenacionAccess() {
		return pExprConcatenacion;
	}
	
	public ParserRule getExprConcatenacionRule() {
		return getExprConcatenacionAccess().getRule();
	}
	
	//ExprAritmetica:
	//    '('(operadorAr = ('+' | '-' | '/' | '*' | '%')  (exprAr+=(Expresion))+) ')' |  (Nota | SubNota)
	//;
	public ExprAritmeticaElements getExprAritmeticaAccess() {
		return pExprAritmetica;
	}
	
	public ParserRule getExprAritmeticaRule() {
		return getExprAritmeticaAccess().getRule();
	}
	
	//ExprLogica:
	//   (Negado ?= '!')? exprLog=(ExprLogicaOperadores | Ritmo | ExprComparacion )
	//;
	public ExprLogicaElements getExprLogicaAccess() {
		return pExprLogica;
	}
	
	public ParserRule getExprLogicaRule() {
		return getExprLogicaAccess().getRule();
	}
	
	//ExprLogicaOperadores:
	//    (('('(operadorLog = ( '&&' | '||' ) (exprLogs+=(Expresion))+) ')' ))
	//;
	public ExprLogicaOperadoresElements getExprLogicaOperadoresAccess() {
		return pExprLogicaOperadores;
	}
	
	public ParserRule getExprLogicaOperadoresRule() {
		return getExprLogicaOperadoresAccess().getRule();
	}
	
	//ExprComparacion:
	//    '('(operadorComp = ('<' | '>' | '<=' | '>=' | '==' | '~=') exprComIzq=(Expresion) exprComDer=(Expresion)) ')'
	//;
	public ExprComparacionElements getExprComparacionAccess() {
		return pExprComparacion;
	}
	
	public ParserRule getExprComparacionRule() {
		return getExprComparacionAccess().getRule();
	}
	
	//Primitivo:
	//    tipo = ('Melodia' |  'Nota' | 'SubNota' | 'Ritmo')
	//;
	public PrimitivoElements getPrimitivoAccess() {
		return pPrimitivo;
	}
	
	public ParserRule getPrimitivoRule() {
		return getPrimitivoAccess().getRule();
	}
	
	//Nota:
	//    x = INT
	//;
	public NotaElements getNotaAccess() {
		return pNota;
	}
	
	public ParserRule getNotaRule() {
		return getNotaAccess().getRule();
	}
	
	//Melodia:
	//    x = STRING
	//;
	public MelodiaElements getMelodiaAccess() {
		return pMelodia;
	}
	
	public ParserRule getMelodiaRule() {
		return getMelodiaAccess().getRule();
	}
	
	//SubNota:
	//    x = Double
	//;
	public SubNotaElements getSubNotaAccess() {
		return pSubNota;
	}
	
	public ParserRule getSubNotaRule() {
		return getSubNotaAccess().getRule();
	}
	
	//Double returns ecore::EDouble:
	//    INT '.' INT
	//;
	public DoubleElements getDoubleAccess() {
		return pDouble;
	}
	
	public ParserRule getDoubleRule() {
		return getDoubleAccess().getRule();
	}
	
	//Ritmo:
	//    x = ('Cuarto' | 'Octavo')
	//;
	public RitmoElements getRitmoAccess() {
		return pRitmo;
	}
	
	public ParserRule getRitmoRule() {
		return getRitmoAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
